### ISSUE TITLE
Release 0.4 is broken

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/FALCON-integrate#10]
Failing builds (on same commit):
- https://travis-ci.org/PacificBiosciences/FALCON-integrate/builds/79020458
- https://travis-ci.org/PacificBiosciences/FALCON-integrate/builds/79183004

Jason, Please use pull-requests to update FALCON-integrate. That way, our integration tests will run.

I have deleted the 0.4 tag until this issue is resolved. I don't even know what it was. An annotated tag? It was hard to pull into my repo, so something was unusual about it. Could you tell me what command you used to create it?

I have pushed that commit as a temporary branch called 'tag-0.4'. I _think_ the problem is that `fc_run.py` is no longer installed with the rest of the scripts. Maybe you could look into it as I don't have time right now. (Working in FALCON-pbsmrtpipe, which is very very tedious.)

**Comment by pb-jchin** [comment]
I just push a tag the master head should not change, can you check?
I did not touch anything in Falcon-Integrate but only the reference.  why fc_run.py is missing? I can check again.

**Comment by pb-cdunn** [comment]
"master" is fine. But the tag creates an official "release". Pushing the tag pushed a commit, which caused a Travis build that I happened to notice. Email on build-failures would be another solution to this, but I prefer pull-requests.

I don't know why fc_run.py is missing.

I was unable to build h5py in TravisCI (at least with caching, which is important), so I am experimenting with CircleCI now. pbsmrtpipe/pbcommand have a _lot_ of dependencies. So this is taking a lot longer than I'd hoped. I really don't have any spare time today.

**Comment by pb-jchin** [comment]
fc_run.py was deleted here https://github.com/pb-cdunn/FALCON/commit/2c1ce98e6f930c357db035e00358003ea86e3fd0#diff-8a6982a2729e84f0c106f6e34403614f 
I will rescue it.

**Comment by pb-cdunn** [comment]
No big deal. It's ok to break master. We just want to avoid issuing a bad release, since it would lead to a flurry of complaints by users.

I've copied mkocher's circleci.yaml and tested CircleCI. The initial build time including pbsmrtpipe is terrible: 8.5m. But because of caching, the 2nd build is only 0.5m! Very reasonable. That doesn't including any FALCON parts, but we should be just a couple minutes altogether. So if I can get everything to compile in CircleCI, I might move our integration tests from TravisCI to CircleCI.

On the other hand,  we will have tests running within PacBio. I just like to catch bugs as early as possible. We'll see...

My immediate priority is to get some "chunking" in FALCON-pbsmrtpipe.
