### ISSUE TITLE
LAmerge: PT-point spacing conflict falcon after setting -s100 to rerun 9 Daligner job

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON-integrate#104]
Hi,

In the first step there are 9 / 1103 jobs that failed due to LAcheck showing "Duplicate overlap".  Based on issue #444 I reran each job successfully by setting -s100 from -s1000.

Now the jobs proceed fine but failed at LAmerge stage:

![image](https://cloud.githubusercontent.com/assets/5182142/20258160/34b7c76c-aa89-11e6-91a1-69f0025a06f0.png)

It seems that I really can't just delete _done.exit and create fake _done files as they may be too many data loss? Out of 15 jobs already 7 failed with the same issue. How should I proceed?  I would like to ignore the 9 jobs if possible as it really took a long time at da stage.

**Comment by ishengtsai** [comment]
Note I also ran with the latest aligner (with -s1000) and LAcheck and the duplicate overlap problem didn't go away.

**Comment by pb-jchin** [comment]
`LAcheck` still has its own bug. You can turn it off if you like. However, you might have some corrupted files (maybe your file system can't handle the throughput).  Make sure you use consistent `-s` and re-run the pipeline and ignore `LAcheck` to how it works.

**Comment by ishengtsai** [comment]
So how do I turn it off with the exiting 9 failed jobs ?

Rerun rj_job.sub.sh in each job_xx folder with

```
set +e # Add this 
LAcheck -v raw_reads *.las
set -e # Add this
```

?

**Comment by pb-cdunn** [comment]
How old is your version of `DALIGNER`? Please tell us the git-commit for the DALIGNER submodule. In theory, this has been fixed.

**Comment by ishengtsai** [comment]
I fixed this issue by rerunning everything with -s600 instead.

**Comment by pb-cdunn** [comment]
> How old is your version of DALIGNER? Please tell us the git-commit for the DALIGNER submodule. In theory, this has been fixed.

If you could answer that question, it could help us to know whether this is something we still need to work on with GeneMyers.

**Comment by ishengtsai** [comment]
How do I check it?

**Comment by pb-cdunn** [comment]
It's installed from GitHub. You can run `git rev-parse HEAD` in the git-clone it was installed from.
