### ISSUE TITLE
[Question]How can only run the error correction step?

### ISSUE THREAD

**Issue by simoncchu** [PacificBiosciences/FALCON-integrate#108]
Hi, I have successfully installed FALCON-integrate, and it works well. I wonder how can I only run the error correction step without trigger the filtering and assembly? Thank you.

**Comment by pb-cdunn** [comment]
input_type = preads

But I might have broken that recently. We do not regularly test that code-path. If it doesn't work and you are able to find a solution, feel free to submit a pull-request in **FALCON**.

**Comment by pb-jchin** [comment]
In the old code, IIRC, there is a configurable option called "target" which can be set to terminate the workflow early but it is rarely used.  If you really want to just run the error correct part, create a `1-preads_ovl` and make it un-writable for now.
