### ISSUE TITLE
How to tell whether FALCON-integrate is successfully installed.

### ISSUE THREAD

**Issue by Mr-Inamn** [PacificBiosciences/FALCON-integrate#112]
Hi,
Based on the easy way installation, I have run every step. But I do not know the standard that whether I have successfully installed FALCON-intefrate. When I run make -j test, the last standard output is as follows:

>     Installed /public/home/lijing/software/FALCON-integrate/FALCON
> Successfully installed falcon-kit networkx-1.10
> Cleaning up...
> make[2]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'
> make check
> make[2]: Entering directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'
> python -c 'import pypeflow.simple_pwatcher_bridge; print pypeflow.simple_pwatcher_bridge'
> <module 'pypeflow.simple_pwatcher_bridge' from '/public/home/lijing/software/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.py'>
> python -c 'import falcon_kit; print falcon_kit.falcon'
> <CDLL '/public/home/lijing/software/FALCON-integrate/FALCON/ext_falcon.so', handle 10f9730 at 2abd82d964d0>
> make[2]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'
> make[1]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'

And when I run make test,  the last standard output is as follows:

> 2016-12-14 02:57:47,181[INFO] starting job Job(jobid='Pba8c6bc94c04a9', cmd='/bin/bash run.sh', rundir='/public/home/lijing/software/FALCON-integrate/FALCON-examples/run/synth0/2-asm-falcon', options={'job_queue': 'production', 'sge_option': '-pe smp 24 -q production', 'job_type': 'local'})
> 2016-12-14 02:57:47,203[INFO] Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pba8c6bc94c04a9', cmd='/bin/bash run.sh', rundir='/public/home/lijing/software/FALCON-integrate/FALCON-examples/run/synth0/2-asm-falcon', options={'job_queue': 'production', 'sge_option': '-pe smp 24 -q production', 'job_type': 'local'}), lang_exe='/bin/bash'))
> 2016-12-14 02:57:47,203[INFO] sleep 0.1s
> 2016-12-14 02:57:47,304[INFO] sleep 0.2s
> 2016-12-14 02:57:47,505[INFO] sleep 0.3s
> 2016-12-14 02:57:47,806[INFO] sleep 0.4s
> 2016-12-14 02:57:48,207[INFO] sleep 0.5s
> 2016-12-14 02:57:48,708[INFO] sleep 0.6s
> 2016-12-14 02:57:49,309[INFO] recently_satisfied: set([Node(2-asm-falcon)])
> 2016-12-14 02:57:49,310[INFO] Num satisfied in this iteration: 1
> 2016-12-14 02:57:49,310[INFO] Num still unsatisfied: 0
> make[3]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-examples'
> make -C run/synth0 test
> make[3]: Entering directory `/public/home/lijing/software/FALCON-integrate/FALCON-examples/run/synth0'
> ./check.py
> shifted by 3269 (rc)
> make[3]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-examples/run/synth0'
> make[2]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-examples'
> make[1]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'

Does this mean that I have successfully installed it? And how to analyze the results? Many thanks.

**Comment by pb-cdunn** [comment]
```
./check.py
shifted by 3269 (rc)
```
That means the test passed. The 5kbp circular reference was recreated exactly, rotated by 3269 bases.

You can see results in `2-asm-falcon`, e.g. `p_ctg.fa`
