### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by Mr-Inamn** [PacificBiosciences/FALCON-integrate#115]
Hi,
I have a problem about the FALCON environment variables setting. My way is put the 

`PATH=$PATH:/public/home/lijing/software/FALCON-integrate/fc_env/bin`

into my .bashrc file. 
But when I closed the server and re-connect the server, then run fc_run.py, something wrong happened. The wrong message is as follows. However, when I re-install the falcon based on the easy way instructions, everything is normal again. Does it mean that I need to re-install falcon every time when I need to run it? If not, how to set the FALCON environment variables without using the absolute path?

> Traceback (most recent call last):
>   File "/public/home/lijing/software/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
>     __import__('pkg_resources').require('falcon-kit==0.7+git.3b90cca3af5435b2a3b11e5f529befe718191368')
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
>   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
> pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.3b90cca3af5435b2a3b11e5f529befe718191368' distribution was not found and is required by the application

Many thanks.

**Comment by pb-cdunn** [comment]
Depending on how you isntalled, you might need `PYTHONUSERBASE` in your .bashrc too. See `env.sh`.

**Comment by Mr-Inamn** [comment]
The content of env.sh is as follows:
```
FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib
But how to set it? 
```
I tried adding `source /public/home/lijing/software/FALCON-integrate/env.sh` into my` .bashrc`. But it still did not work. However, when I went into ` /public/home/lijing/software/FALCON-integrate`, then `source env.sh`, everything is ok. So can you tell me how to set the falcon `PYTHONUSERBASE` into my `.bashrc`?

**Comment by pb-cdunn** [comment]
`env.sh` used `$(pwd)`, so it works only if you are in that directory. You can substitute `$(pwd)` with `/public/home/lijing/software/FALCON-integrate`.
