### ISSUE TITLE
Falcon install problem

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON-integrate#118]
Hi,

For some reason I had some problem trying to install the new version `git checkout master`. This is similar to issue #87 .

`make -j all`

![image](https://cloud.githubusercontent.com/assets/5182142/21602083/63b3a086-d1cb-11e6-9687-36f283a278b3.png)

`git rev-parse HEAD`
gives `a72f47c4600fb31c993151c1d03c1787ba42b161`

env.sh is as follows and have been successfully incorporated:
![image](https://cloud.githubusercontent.com/assets/5182142/21602130/c418adea-d1cb-11e6-81ae-c47e64dcce00.png)

Help would be appreciated. And happy new year!

**Comment by pb-cdunn** [comment]
Did you source `env.sh` into your shell? What is `PYTHONUSERBASE`?

Can you find the pypeflow package somewhere under your PYTHONUSERBASE directory tree?

Your screen-capture shows "Successfully installed falcon-kit". What about pypeflow? Was that successfully installed? Where?

**Comment by ishengtsai** [comment]
Yes I did. 
`echo $PYTHONUSERBASE`  
`/home/ijt/bin/FALCON-integrate/fc_env`

pypeflow package is found
`cd ~/bin/FALCON-integrate/fc_env/lib/python3.5/site-packages`
![image](https://cloud.githubusercontent.com/assets/5182142/21630839/00cf565e-d270-11e6-9e7b-ea25538e80ec.png)




pypeflow was successfully installed:
![image](https://cloud.githubusercontent.com/assets/5182142/21630827/d866f50a-d26f-11e6-90b3-e19e5fd46726.png)

**Comment by pb-cdunn** [comment]
> cd ~/bin/FALCON-integrate/fc_env/lib/python3.5/site-packages

We do not support python3. Also, if `python` in your `$PATH` is python2, then `python -c 'print hi'` might run a different version of python than you used when you installed.
