### ISSUE TITLE
FALCON stopped with no error messages in */pwatcher.dir/stderr

### ISSUE THREAD

**Issue by IEkAdN** [PacificBiosciences/FALCON-integrate#120]
Hello,

I had suffered from the LAcheck problem (https://github.com/PacificBiosciences/FALCON/issues/445) before,
so I reran FALCON-integrate(cd37700) with 'use_tmpdir = /scratch/...' and the DALIGNER(7c09c81)'s option '-s 100'.
After that, the 'Duplicate overlap' messages disappeared,
but the assembly stopped in a different way at the step 0-rawreads (No files were generated in 1-preads_ovl/)
The problem is that there are no error messages by FALCON in */pwather.dir/stderr and these stderr files all ended with 'returned: 0'.
I have ever run FALCON with the other datasets, and it successfly comleted aseemblies with them,
so I think our system environment might not be the only cause of this problem.
I uploaded '0-rawreads/job_0000/pwatcher.dir/stderr' and 'all.log'.
Is LAcheck still causing any problems, or do you have any other idea ?

[all.log.zip](https://github.com/PacificBiosciences/FALCON-integrate/files/699240/all.log.zip)
[stderr.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/699242/stderr.txt)

**Comment by pb-cdunn** [comment]
You have way too much "simple_pwatcher" debug logging. Is that the default? You can control the debug output via a standard python logging config, which you can google. Provide that config as the 2nd argument to `fc_run`. An example is in `FALCON-examples/logging.ini`

I didn't notice any actual error from that log. But I see that you were running parallel daligner jobs, e.g. `0-rawreads/job_000b`. I suggest looking into that directory to see how much progress you have made.

**Comment by IEkAdN** [comment]
Thank you for your quick response.

I'm totally new to python logging module, and I've never changed logging settings.
I'm OK with rerunning FALCON with the example config file,
but can the too much logging be the cause of this problem?

I uploaded `0-rawreads/job_000b/pwatcher.dir/stderr`.
This kind of log files (`0-rawreads/*/pwatcher.dir/stderr`) all show that each job seems to be completed without any errors.
Do you have any idea with this log?

[stderr_000b.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/700386/stderr_000b.txt)

**Comment by pb-cdunn** [comment]
returned: 0

That particular job completed successfully. The top-level log tells you which job failed, if any.

Also, the whole thing is a bit easier to work with if you have more, smaller jobs. I would reduce the `-B` option of **HPC.daligner** down to its default of `-B4`.

https://dazzlerblog.wordpress.com/command-guides/daligner-command-reference-guide/

You should either read the standard Python logging config help online, or find someone who is more familiar with Python. We cannot offer that level of support.
