### ISSUE TITLE
error while running test data sets 

### ISSUE THREAD

**Issue by amit4mchiba** [PacificBiosciences/FALCON-integrate#124]
Hi, Please advice me. I am new to Falcon, and struggling to run this software. Follwing instructions, i was able to install falcon, recieved error message when started running test run. Its strange that while i am able to run test datasets locally, it was not working on grid. 
Anyways, i started running ecoli datasets, and after running for quite some time, it ended up in error. While starting, it reported 60 unstatisfied jobs, and at the end resolved all but 3. And then i got the error message saying that we have 2 failures. 3 tasks remain unsatisfied. I am not sure why? 

Please find below the details of error message. Please advice me how to resolve it. Thanks in advance
```
2017-02-03 03:32:28,191 - pypeflow.simple_pwatcher_bridge - INFO - 
recently_satisfied: set([Node(0-rawreads/job_000b)])
2017-02-03 03:32:28,191 - pypeflow.simple_pwatcher_bridge - INFO - Num 
satisfied in this iteration: 1
2017-02-03 03:32:28,192 - pypeflow.simple_pwatcher_bridge - INFO - Num 
still unsatisfied: 4
2017-02-03 03:32:28,192 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.1s
2017-02-03 03:32:28,293 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.2s
2017-02-03 03:32:28,494 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.3s
2017-02-03 03:32:28,795 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.4s
2017-02-03 03:32:29,197 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.5s
2017-02-03 03:32:29,697 - pypeflow.simple_pwatcher_bridge - INFO - sleep 
0.6s
2017-02-03 03:32:30,299 - pypeflow.simple_pwatcher_bridge - INFO - 
recently_satisfied: set([Node(0-rawreads/job_0009)])
2017-02-03 03:32:30,299 - pypeflow.simple_pwatcher_bridge - INFO - Num 
satisfied in this iteration: 1
2017-02-03 03:32:30,300 - pypeflow.simple_pwatcher_bridge - INFO - Num 
still unsatisfied: 3
```
```py
Traceback (most recent call last):
  File "/lustre1/home/amit-rai8chiba/Falcon/VM_env/bin/fc_run.py", line 
6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/FALCON/src/
py_scripts/fc_run.py", line 5, in <module>
    main(sys.argv)
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/FALCON/
falcon_kit/mains/run1.py", line 461, in main
    main1(argv[0], args.config, args.logger)
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/FALCON/
falcon_kit/mains/run1.py", line 136, in main1
    input_fofn_plf=input_fofn_plf,
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/FALCON/
falcon_kit/mains/run1.py", line 234, in run
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/pypeFLOW/
pypeflow/simple_pwatcher_bridge.py", line 226, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/lustre1/home/amit-rai8chiba/Falcon/FALCON-integrate/pypeFLOW/
pypeflow/simple_pwatcher_bridge.py", line 297, in _refreshTargets
    failures, len(unsatg)))
Exception: We had 2 failures. 3 tasks remain unsatisfied.
make: *** [run-ecoli] ??? 1
```

**Comment by pb-cdunn** [comment]
You need to learn which tasks failed and then examine the stderr for those specific tasks in their run directories. Maybe the ERROR messages appear earlier in the log? If not, try `ls` on the task directories until you find something missing key files.

If this turns out to be an error with daligner/LAmerge, your small test-case could be helpful to Gene Myers.

**Comment by wsuplantpathology** [comment]
Hi pb-cdunn:

I think I got similar issues #129 . Following your suggestions here, I got 3 jobs with this:
```
[ERROR]Task Node(0-rawreads/job_0287) failed with exit-code=256
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 759
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/job_0287)])
```
I wonder, since I found these 3 failed jobs, what should I do now? 
Thanks.
Chongjing

**Comment by wsuplantpathology** [comment]
Hi  @pb-cdunn again:

I checked the stderr files of my three failed jobs. I think I found something interesting. In stderr files of all failed jobs I found this information:
```raw_reads.25.raw_reads.64.C3: Duplicate overlap (141622 vs 358350)```
While I never see this in successful jobs. Are these particular reads caused the error? If so, can we just delete these reads? After deletion, how can we continue the analyses without re-starting from beginning?

many thanks
chongjing

**Comment by wsuplantpathology** [comment]
I think I solved the problem. If someone got same problem, here is what I did: 
1) open ./0-rawreads/job_*/task.json, change `"skip_checks": false,` to `"skip_checks": true,`,
2) open ./0-rawreads/job_*/rj_*.sh, change all `LAcheck` to `#LAcheck`,
3) run /bin/bash rj_*.sh,
4) open ./0-rawreads/job_*/pwatcher.dir/stderr, change `returned: 256` to 

`touch /path/to/0-rawreads/run.sh.done`
`+ touch /path/to/0-rawreads/run.sh.done`
  ` returned: 0`,

5) open fc_run.ctg, put `skip_checks = true`,
6) re-start falcon.

**Comment by pb-jchin** [comment]
@wsuplantpathology 
Thanks for sharing the solutions with others.

**Comment by amit4mchiba** [comment]
@wsuplantpathology 
May i ask how you did these changes in all files in one go. You mean that you changed each file one at a time. Also, while changing these will help but new files being generated will still have same issues. How to resolve them now. Is there something that can be done in the config file that may help?

**Comment by wsuplantpathology** [comment]
@amit4mchiba 
Usually only few jobs failed (fo me, 3 out of >900), so I manually re-ran them individually. Unfortunately, I don't know how to do many failed jobs, e.g. in config file. For you I suggest to run the job and wait until the job stops, then check how many and what jobs are failed, then do as what I shown. Good luck.

**Comment by amit4mchiba** [comment]
Thanks for your advice. I checked my jobs and have got similar errors. I am trying your ways and will update here. Thanks for your share
