### ISSUE TITLE
Error message: Job was rejected because job requests unknown queue "default".

### ISSUE THREAD

**Issue by stueber** [PacificBiosciences/FALCON-integrate#128]
Dear all,
We are just trying to get FALCON to run for the first time.
In the file fc_run.cfg we specify the SGE "main.q" queue like this:

jobqueue = main.q
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

But when falcon starts we get the error message: 
Unable to run job: Job was rejected because job requests unknown queue "default".
Exiting.

I also tried to the put main.q in single or double quotes without effect.

Any ideas?

Greetings

Kurt

**Comment by pb-cdunn** [comment]
The `-q` options have become "magical". They are substituted according to the `job_queue` variable in Python. So the substitution done in your `.ini` file (via `%(jobqueue)s`) is irrelevant (I think).

If you simply use `job_queue` instead of `jobqueue`, everything should work for you.
