### ISSUE TITLE
how to continue a failed running

### ISSUE THREAD

**Issue by wsuplantpathology** [PacificBiosciences/FALCON-integrate#130]
Hi FALCON:

Previously, when I was running Falcon I got three unsatisfied jobs caused by LAcheck issues. After I manually  re-ran these unsatisfied jobs, they are all satisfied now. I wonder, how can I continue to run the following steps from where I failed, without starting from all the beginning? Thanks.

Best,
chongjing

**Comment by pb-cdunn** [comment]
Same as #124.
