### ISSUE TITLE
[Error] E. coli test failed

### ISSUE THREAD

**Issue by Leelouh** [PacificBiosciences/FALCON-integrate#136]
Hi, I installed Falcon on my home directory.
But when I try to test it with e. coli data, I have this error : 

> ~/local/falcon/FALCON/src/py_scripts/fc_run.py: line 1: from: command not found
> import: unable to open X server `' @ import.c/ImportImageCommand/359.
> ~/local/falcon/FALCON/src/py_scripts/fc_run.py: line 5: syntax error near unexpected token `sys.argv'
> ~/local/falcon/FALCON/src/py_scripts/fc_run.py: line 5: `    main(sys.argv)'

Thank you for your help

**Comment by pb-jchin** [comment]
You will need to add the executable path to your running environment. I think the installation guide has the instruction about using `source` command to incorporate the environment.

**Comment by LauraHelou** [comment]
I try to do it, but I have the same error. I work on a cluster and have to install tools on my home directory. 
So first, I tried to export the path, same error.
After I used the source command and saw this error : 

> 
> -bash: from: command not found
> import: unable to open X server `' @ import.c/ImportImageCommand/359.
> -bash: local/falcon/FALCON/src/py_scripts/fc_run.py: line 5: syntax error near unexpected token `sys.argv'
> -bash: local/falcon/FALCON/src/py_scripts/fc_run.py: line 5: `    main(sys.argv)'

Thank you for your help

**Comment by pb-jchin** [comment]
for unknown reason, you were trying to run the python script with a bash interpreter.

**Comment by LauraHelou** [comment]
I used pyenv. But ok, thank you for your help.
