### ISSUE TITLE
Some reads are not included in the assembly

### ISSUE THREAD

**Issue by Liukvr** [PacificBiosciences/FALCON-integrate#138]
Hi,
i just assembly an algae genome, with expected genome size of 40Mb. I have noticed that some reads (72,782 on a total of 619,961 ) are not included in the assembly. In these reads is present a gene of our interest and i would like to include it in the final assembly. 
How can i manage this issue?  
Should i  assembly them separately or repeat the assembly changing the parameters? 

Here you can find the configuration file that i used:
https://www.dropbox.com/s/5nmbdoj5yctruzq/fc_run.cfg?dl=0

Thanks in advance,

Luca

**Comment by pb-jchin** [comment]
You can take the reads that is not in the assembly and re-assemble them with a more relaxed parameters for repeats. Some reads are not used for various reasons.  If they are in high copy repeat regions, you can re-assemble those reads with a more repeat tolerant parameters.

**Comment by Liukvr** [comment]
Thanks a lot for the answer.

I'm following your advice tryng to assemble those reads separately with more relaxed parameters.
To do this i increased --max_cov and --max_diff, is that correct or do you suggest to modify other parameters?

thanks in advance,

Luca
