### ISSUE TITLE
[3932]$('lfs setstripe -c 12 /public/home/lijing/software/FALCON-integrate')

### ISSUE THREAD

**Issue by Mr-Inamn** [PacificBiosciences/FALCON-integrate#145]
When I run fc_run.py, the error is as titled. So what is lfs? How to set it?

**Comment by Mr-Inamn** [comment]
The detailed log is as follows. Can anybody help me fix this problem? Many thanks.
```
./fc_env/bin/fc_run.py
[33614]$('lfs setstripe -c 12 /public/home/lijing/software/FALCON-integrate')
sh: lfs: command not found
[33614]WARNING: Call 'lfs setstripe -c 12 /public/home/lijing/software/FALCON-integrate' returned 32512.
usage: fc_run.py [-h] config [logger]
fc_run.py: error: too few arguments
```

**Comment by DongnaMa** [comment]
Hi,did you solved this problem? I encountered the same problem，can you give me some advices?

**Comment by Mr-Inamn** [comment]
Sorry, I haven't solved it.

Regards
---
Jing Li
Life Science Institute
Zhejiang University
Hangzhou,Zhejiang,310058
PR China

**Comment by pb-cdunn** [comment]
The "lfs stripe" message is only a warning. It means that you are not running in lustre. Ignore that.

You need to provide the `.cfg` file as the first argument. See
* https://github.com/pb-cdunn/FALCON-examples/blob/master/run/synth0/makefile
