### ISSUE TITLE
Install latest version of FALCON

### ISSUE THREAD

**Issue by admerait** [PacificBiosciences/FALCON-integrate#153]
I was following the instruction on installing the latest version of FALCON. When I execute the "make -j all". It ended with error. I am running python 2.7.12. I also tried 2.7.9, and it failed as well. Please help.

make -C ./FALCON-make/ all
make[1]: Entering directory `/tools/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/tools/FALCON-integrate/FALCON-make'
mkdir -p /tools/FALCON-integrate/fc_env/bin
which python
/tools/python-2.7/bin/python
echo "PYTHONUSERBASE=/tools/FALCON-integrate/fc_env"
PYTHONUSERBASE=/tools/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/tools/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/tools/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/tools/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/tools/python-2.7/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Requirement already up-to-date: pip in /tools/python-2.7/lib/python2.7/site-packages
pip install --user --upgrade setuptools # needed when --edit is used
Requirement already up-to-date: setuptools in /tools/python-2.7/lib/python2.7/site-packages
pip install --user nose pytest # for running tests while building
Requirement already satisfied: nose in /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages
Requirement already satisfied: pytest in /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages
Requirement already satisfied: py>=1.4.33 in /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: setuptools in /tools/python-2.7/lib/python2.7/site-packages (from pytest)
make[2]: Leaving directory `/tools/FALCON-integrate/FALCON-make'
make install # This will double -D_GNU_SOURCE, but that is ok for now.
make[2]: Entering directory `/tools/FALCON-integrate/FALCON-make'
make -C /tools/FALCON-integrate/DAZZ_DB all
make -C /tools/FALCON-integrate/DAMASKER all
make -C /tools/FALCON-integrate/DEXTRACTOR all
cd /tools/FALCON-integrate/pypeFLOW; pip uninstall -v .; pip install -v --user --edit .
TODO: copy vs. symlink?
make -C /tools/FALCON-integrate/nim-falcon/src -j1 all
ln -sf /tools/FALCON-integrate/git-sym/git-sym /tools/FALCON-integrate/fc_env/bin/git-sym
make[3]: Entering directory `/tools/FALCON-integrate/DEXTRACTOR'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/tools/FALCON-integrate/DEXTRACTOR'
PREFIX=/tools/FALCON-integrate/fc_env make -C /tools/FALCON-integrate/DEXTRACTOR symlink
make[3]: Entering directory `/tools/FALCON-integrate/DAMASKER'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/tools/FALCON-integrate/DAMASKER'
PREFIX=/tools/FALCON-integrate/fc_env make -C /tools/FALCON-integrate/DAMASKER symlink
make[3]: Entering directory `/tools/FALCON-integrate/nim-falcon/src'
nim --threads:on --threadAnalysis:off --verbosity:2 -d:release  --tlsemulation:on --out:fc_rr_hctg_track2.exe c fc_rr_hctg_track2.nim
make[3]: Entering directory `/tools/FALCON-integrate/DEXTRACTOR'
ln -sf /tools/FALCON-integrate/DEXTRACTOR/dexta /tools/FALCON-integrate/DEXTRACTOR/undexta /tools/FALCON-integrate/fc_env/bin
make[3]: nim: Command not found
make[3]: *** [fc_rr_hctg_track2.exe] Error 127
make[3]: Leaving directory `/tools/FALCON-integrate/nim-falcon/src'
make[2]: *** [install-nim-falcon] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory `/tools/FALCON-integrate/DAMASKER'
ln -sf /tools/FALCON-integrate/DAMASKER/datander /tools/FALCON-integrate/DAMASKER/TANmask /tools/FALCON-integrate/DAMASKER/REPmask /tools/FALCON-integrate/DAMASKER/HPC.TANmask /tools/FALCON-integrate/DAMASKER/HPC.REPmask /tools/FALCON-integrate/fc_env/bin
make[3]: Entering directory `/tools/FALCON-integrate/DAZZ_DB'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/tools/FALCON-integrate/DAZZ_DB'
make[3]: Leaving directory `/tools/FALCON-integrate/DEXTRACTOR'
PREFIX=/tools/FALCON-integrate/fc_env make -C /tools/FALCON-integrate/DAZZ_DB symlink
make[3]: Leaving directory `/tools/FALCON-integrate/DAMASKER'
make[3]: Entering directory `/tools/FALCON-integrate/DAZZ_DB'
ln -sf /tools/FALCON-integrate/DAZZ_DB/fasta2DB /tools/FALCON-integrate/DAZZ_DB/DB2fasta /tools/FALCON-integrate/DAZZ_DB/DBsplit /tools/FALCON-integrate/DAZZ_DB/DBdust /tools/FALCON-integrate/DAZZ_DB/Catrack /tools/FALCON-integrate/DAZZ_DB/DBshow /tools/FALCON-integrate/DAZZ_DB/DBstats /tools/FALCON-integrate/DAZZ_DB/DBrm /tools/FALCON-integrate/DAZZ_DB/simulator /tools/FALCON-integrate/DAZZ_DB/fasta2DAM /tools/FALCON-integrate/DAZZ_DB/DAM2fasta /tools/FALCON-integrate/DAZZ_DB/DBdump /tools/FALCON-integrate/DAZZ_DB/rangen /tools/FALCON-integrate/fc_env/bin
ln -sf /tools/FALCON-integrate/DAZZ_DB/libdazzdb.a /tools/FALCON-integrate/fc_env/lib
ln -sf /tools/FALCON-integrate/DAZZ_DB/DB.h /tools/FALCON-integrate/DAZZ_DB/QV.h /tools/FALCON-integrate/fc_env/include
make[3]: Leaving directory `/tools/FALCON-integrate/DAZZ_DB'
Obtaining file:///tools/FALCON-integrate/pypeFLOW
  Running setup.py (path:/tools/FALCON-integrate/pypeFLOW/setup.py) egg_info for package from file:///tools/FALCON-integrate/pypeFLOW
    Running command python setup.py egg_info
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
  Source in /tools/FALCON-integrate/pypeFLOW has version 1.0.0, which satisfies requirement pypeflow==1.0.0 from file:///tools/FALCON-integrate/pypeFLOW
Requirement already satisfied: networkx<=1.11,>=1.7 in /tools/python-2.7/lib/python2.7/site-packages (from pypeflow==1.0.0)
Requirement already satisfied: decorator>=3.4.0 in /tools/FALCON/.eggs/decorator-4.0.10-py2.7.egg (from networkx<=1.11,>=1.7->pypeflow==1.0.0)
Installing collected packages: pypeflow
  Found existing installation: pypeflow 1.0.0
    Uninstalling pypeflow-1.0.0:
      Removing file or directory /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
      Removing pth entries from /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /tools/FALCON-integrate/pypeFLOW
      Successfully uninstalled pypeflow-1.0.0
  Running setup.py develop for pypeflow
    Running command /tools/python-2.7/bin/python -c "import setuptools, tokenize;__file__='/tools/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=
    running develop
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
    running build_ext
    Creating /tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link (link to .)
    Adding pypeflow 1.0.0 to easy-install.pth file
    Installing pwatcher-pypeflow-example script to /tools/FALCON-integrate/fc_env/bin
    Installing heartbeat-wrapper script to /tools/FALCON-integrate/fc_env/bin
    Installing pwatcher-main script to /tools/FALCON-integrate/fc_env/bin
    Installed /tools/FALCON-integrate/pypeFLOW
Successfully installed pypeflow
Cleaning up...
make[2]: Leaving directory `/tools/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tools/FALCON-integrate/FALCON-make'
make: *** [all] Error 2

**Comment by pb-cdunn** [comment]
You need to install the `nim` compiler first: https://nim-lang.org/install.html
