### ISSUE TITLE
falcon just "sleeps"

### ISSUE THREAD

**Issue by mike2vandy** [PacificBiosciences/FALCON-integrate#154]
I just got a new install of FALCON-integrate (0.5). This is a local machine, i adjusted the local fc_run_ecoli_local.cfg and the short question is why would falcon indefinitely "sleep"?

**Comment by pb-cdunn** [comment]
Hard to debug from here. And those examples might need to be updated.

I always suggest running the 'synth0' test first, which uses a tiny 5000-base artificial genome.
* https://github.com/pb-cdunn/FALCON-examples
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
