### ISSUE TITLE
falcon-unzipped stuck in 1-hasm

### ISSUE THREAD

**Issue by leleory** [PacificBiosciences/FALCON-integrate#155]
Hello all,
We got our genome assembled by Falcon and now I try to run Falcon-unzipped. The pipeline got the reads, finished with 0-phasing and now doing 1-hasm, but it is not submitting any jobs and it appears to got stuck in the rid-to-phase-all process.  The main script is running on the headnode for over a day now, but jobs are not getting submitted.

The mypwatcher error message list the jobs which look like the following:
"2017-11-02 04:16:51,797 - root - DEBUG - Checking existence of u'/test/falcon/run/3-unzip/0-phasing/000176F/rid_to_phase.000176F' with timeout=60"

Any suggestions on what is the issue. I have tried restarting, but the problem remained the same.

Any help would be much appreciated.

Thanks,
Lel

**Comment by pb-cdunn** [comment]
Hopefully this was solved. Latest code seems to work here.
