### ISSUE TITLE
Error when compiling in msgpack4nim.nim

### ISSUE THREAD

**Issue by olekto** [PacificBiosciences/FALCON-integrate#158]
Hi,
I get this error when compiling FALCON-integrate:
FALCON-integrate/nim-falcon/repos/msgpack4nim/msgpack4nim.nim(49, 50) Error: type mismatch: got (uint16) but expected 'uint8'

Also, it would be nice if it was stated explicitly that Nim is needed to install FALCON.

Thank you.

Ole

**Comment by Fyphia** [comment]
Hi,
I also got this error and just got help :
https://github.com/jangko/msgpack4nim/issues/15
Hope this can help you!
Fyphia

**Comment by olekto** [comment]
Thank you Fyphia, that helped. However, I now have another issue:

falcon/consensus/kmer_lookup_c.nim(121, 13) Error: type mismatch: got (int) but expected 'seq_coor_t = int32'
      kmer_bv = kmer_bv or ((int(sa[i.int])) and 0x00000003)

Do you see the same and have you solved it?

Thank you.

Ole

**Comment by olekto** [comment]
I gave up trying to install this, and trying to use the prebuilt binaries from: https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries instead.

**Comment by pb-cdunn** [comment]
Your build-failure was because you had the latest `nim` compiler, which is slightly more strict, and **msgpack4nim** needed to be updated for it. That's all up-to-date now in our repos and in the latest prebuilt binaries.
