### ISSUE TITLE
FALCON-integrate install error

### ISSUE THREAD

**Issue by wangzhennan14** [PacificBiosciences/FALCON-integrate#162]
Hi,
   When I install FALCON-integrate on UNIX platform, there was an error. I have installed it following the userguide. The error was
    Running setup.py develop for falcon-kit
    Running command /public/agis/ruanjue_group/wangzhennan/software/anaconda2/bin/python -c "import setuptools, tokenize;__file__='/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/FALCON/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=
gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/public/agis/ruanjue_group/wangzhennan/software/nim-0.17.2/lib -o /public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_lexbase.o /public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_lexbase.c
Error: execution of an external compiler program 'gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/public/agis/ruanjue_group/wangzhennan/software/nim-0.17.2/lib -o /public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_sequtils.o /public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_sequtils.c' failed with exit code: 1

/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c: In function ‘atomicDec_4E9cxwuunx9aiL7vj9bdy8WvAthreadpool’:
/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c:418: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c:418: error: (Each undeclared identifier is reported only once
/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c:418: error: for each function it appears in.)
/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c: In function ‘slave_ZLEiMrITYl7xqyEhA5iC1g’:
/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src/nimcache/stdlib_threadpool.c:430: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
make[3]: *** [fc_rr_hctg_track2.exe] Error 1
make[3]: Leaving directory `/public/agis/ruanjue_group/wangzhennan/software/FALCON-integrate/nim-falcon/src'
make[2]: *** [install-nim-falcon] Error 2

      What is the matter? Please help to solve it. Thank you very much!
 
                                                                                                                Wang

**Comment by pb-cdunn** [comment]
Same as #163.
