### ISSUE TITLE
FALCON-integrate installation errors

### ISSUE THREAD

**Issue by liuqianhn** [PacificBiosciences/FALCON-integrate#165]
Hi, I followed the easy way in https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation to install FALCON. I have two errors below. Could you please help this? Thanks.

I have following error for `it submodule update --init --recursive`:
> Submodule path 'git-sym': checked out '483836854e1bafb6e40cf17f3a9382efe351daad'
> Submodule 'git-sym-test' (https://github.com/cdunn2001/git-sym-test) registered for path 'git-sym-test'
> Initialized empty Git repository in /home/mysoftware/falcon/FALCON-integrate/git-sym/git-sym-test/.git/
> error: error setting certificate verify locations:
>   CAfile: /home/anaconda2/ssl/cacert.pem
>   CApath: none while accessing https://github.com/cdunn2001/git-sym-test/info/refs
> 
> fatal: HTTP request failed
> Clone of 'https://github.com/cdunn2001/git-sym-test' into submodule path 'git-sym-test' failed
> Failed to recurse into submodule path 'git-sym'

When I run `make -j all`, it has an error below:
> make[3]: Entering directory `/home/mysoftware/falcon/FALCON-integrate/DAMASKER'
> ln -sf /home/mysoftware/falcon/FALCON-integrate/DAMASKER/datander /home/mysoftware/falcon/FALCON-integrate/DAMASKER/TANmask /home/mysoftware/falcon/FALCON-integrate/DAMASKER/REPmask /home/mysoftware/falcon/FALCON-integrate/DAMASKER/HPC.TANmask /home/mysoftware/falcon/FALCON-integrate/DAMASKER/HPC.REPmask /home/mysoftware/falcon/FALCON-integrate/fc_env/bin
> make[3]: Leaving directory `/home/mysoftware/falcon/FALCON-integrate/DAMASKER'
> Directory '.' is not installable. File 'setup.py' not found.
> Exception information:
> Traceback (most recent call last):
>   File "/home/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/home/anaconda2/lib/python2.7/site-packages/pip/commands/uninstall.py", line 61, in run
>     wheel_cache=wheel_cache
>   File "/home/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 201, in from_line
>     "not found." % name
> InstallationError: Directory '.' is not installable. File 'setup.py' not found.
> Directory '.' is not installable. File 'setup.py' not found.

**Comment by pb-cdunn** [comment]
`git submodule update --init --recursive`

That command must succeed before anything else. You might need a more recent version of the `git` executable. Or maybe your Anaconda has done something weird with your SSL certificates. We really cannot help you with this. Maybe talk to a local sysadmin?
