### ISSUE TITLE
length_cutoff value for the preassembly step

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON-integrate#167]
Hi, 
What would be the best `length_cutoff` value for the preassembly step based on the PacBio reads distribution?
```
# NumSamples = 12472585; Min = 500.00; Max = 82508.00
# Mean = 8465.980366; Variance = 29451586.395049; SD = 5426.931582; Median 8071.000000
# each ∎ represents a count of 13507
  500.0000 -   500.0000 [   705]:  (0.01%)
  500.0000 -  1000.0000 [385058]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (3.09%)
 1000.0000 -  2000.0000 [1013071]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (8.12%)
 2000.0000 -  3000.0000 [943488]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (7.56%)
 3000.0000 -  4000.0000 [800818]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (6.42%)
 4000.0000 -  5000.0000 [815184]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (6.54%)
 5000.0000 -  6000.0000 [785206]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (6.30%)
 6000.0000 -  7000.0000 [738391]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (5.92%)
 7000.0000 -  8000.0000 [704700]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (5.65%)
 8000.0000 -  9000.0000 [725012]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (5.81%)
 9000.0000 - 10000.0000 [810799]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (6.50%)
10000.0000 - 11000.0000 [915613]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (7.34%)
11000.0000 - 12000.0000 [856007]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (6.86%)
12000.0000 - 13000.0000 [683033]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (5.48%)
13000.0000 - 14000.0000 [523801]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (4.20%)
14000.0000 - 15000.0000 [402690]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (3.23%)
15000.0000 - 16000.0000 [311128]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (2.49%)
16000.0000 - 17000.0000 [241817]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (1.94%)
17000.0000 - 18000.0000 [186554]: ∎∎∎∎∎∎∎∎∎∎∎∎∎ (1.50%)
18000.0000 - 19000.0000 [142382]: ∎∎∎∎∎∎∎∎∎∎ (1.14%)
19000.0000 - 20000.0000 [110041]: ∎∎∎∎∎∎∎∎ (0.88%)
20000.0000 - 25000.0000 [274829]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (2.20%)
25000.0000 - 30000.0000 [ 76372]: ∎∎∎∎∎ (0.61%)
30000.0000 - 35000.0000 [ 20326]: ∎ (0.16%)
35000.0000 - 40000.0000 [  4733]:  (0.04%)
40000.0000 - 45000.0000 [   697]:  (0.01%)
45000.0000 - 50000.0000 [   114]:  (0.00%)
50000.0000 - 55000.0000 [    14]:  (0.00%)
55000.0000 - 60000.0000 [     0]:  (0.00%)
60000.0000 - 65000.0000 [     0]:  (0.00%)
65000.0000 - 70000.0000 [     0]:  (0.00%)
70000.0000 - 75000.0000 [     0]:  (0.00%)
75000.0000 - 80000.0000 [     1]:  (0.00%)
80000.0000 - 82508.0000 [     1]:  (0.00%)
```
Thank you in advance.

Michal

**Comment by pb-cdunn** [comment]
Unless you have a reason, always use `length_cutoff = -1`. Then it will be calculated for you, based on `seed_coverage` (60 is good) and `genome_size` (which you must estimate).

**Comment by mictadlo** [comment]
I got `functional.GenomeCoverageError: Not enough reads available for desired genome coverage (bases needed=105592659719 > actual=103820015664)`. My plant genome is tetraploid and estimated genome size is 1.8G or 600M for each haploid. Should I use 1.8G or 600M as `genome_size`?

How did you come up for `seed_coverage 60`?

**Comment by pb-cdunn** [comment]
> How did you come up for seed_coverage 60?

Just a guess. I don't have experience with tetraploidy genomes. But you might get some kind of assembly with `seed_coverage=30`. Much below that is not likely to produce anything.

You have a strange peak here:
```
19000.0000 - 20000.0000 [110041]: ∎∎∎∎∎∎∎∎ (0.88%)
20000.0000 - 25000.0000 [274829]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎ (2.20%)
25000.0000 - 30000.0000 [ 76372]: ∎∎∎∎∎ (0.61%)
```
So I wonder about your data.

**Comment by mictadlo** [comment]
The data is based on 102 RSII and 8 SEQUEL SMRT cells. A 20 kb prep library kit was used for both of the sequencing. By any chance, could you please tell me how to check or fix the data and how did you calculated  `seed_coverage=30`?

**Comment by mictadlo** [comment]
The data is based on 102 RSII and 8 SEQUEL SMRT cells. A 20 kb prep library kit was used for both of the sequencing. By any chance, could you please tell me how to check or fix the data and how did you calculated  `seed_coverage=30`?

**Comment by pb-cdunn** [comment]
`30` is just what usually works.

> My plant genome is tetraploid and estimated genome size is 1.8G or 600M for each haploid. Should I use 1.8G or 600M as genome_size?

`600M` is the genome_size. If the haploids are similar enough, you might get a semi-decent assembly with 30x coverage on that. But I don't have any experience with tetraploidy genomes myself. We're making progress on diploids.
