### ISSUE TITLE
falcon.snake

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/FALCON-integrate#168]
Hi,
I cloned FALCON-integrate and I saw `falcon.snake` in `FALCON-integrate/FALCON` folder but when I checked  https://github.com/PacificBiosciences/FALCON it is not in this repository.

Where is this file coming from?

Thank you in advance.

Michal

**Comment by pb-cdunn** [comment]
We tried to use **snakemake** experimentally. In fact, we still dump `foo.snake` when we run. But we ran into the following problems:

* https://bitbucket.org/snakemake/snakemake/issues/577/python-interrupts-snakemake-with-keyerror

So snakemake files should be ignore, until further notice.

**Comment by mictadlo** [comment]
Did you try to use [Common Workflow Language (CWL)](http://www.commonwl.org/)?

**Comment by pb-cdunn** [comment]
> Common Workflow Language (CWL)?

@mictadlo, We could adapt to that pretty easily now. But management has other priorities. If you offer a dumper that we could use, similar to what we tried with snakemake, I think we'd integrate that.
