### ISSUE TITLE
There us no "activate" file. Installation error?

### ISSUE THREAD

**Issue by Jung19911124** [PacificBiosciences/FALCON-integrate#170]
Hi, I am trying to use Falcon_unzip on HGAP4 output for comparison.

Following the instruction here [https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation](url), I tried to install Falcon_unzip.
Then, I got message below. 

I thought this was successful and proceeded to run hgap4_adapt followong the instruction here [http://pb-falcon.readthedocs.io/en/latest/hgap4_adapt.html#running-falcon-unzip](url).

However, I happened to find there is no "activate" file in fc_env/bin directory.

What I have to do ?
Any comments would be appreciated.

Best,
Jung 

######installation process######
> make -C ./FALCON-make/ all
make[1]: Entering directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
mkdir -p /home/jung/Tools/FALCON-integrate/fc_env/bin
which python
/home/jung/.pyenv/shims/python
echo "PYTHONUSERBASE=/home/jung/Tools/FALCON-integrate/fc_env"
PYTHONUSERBASE=/home/jung/Tools/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/home/jung/Tools/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Requirement already up-to-date: pip in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages
pip install --user --upgrade setuptools # needed when --edit is used
Requirement already up-to-date: setuptools in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages
pip install --user nose pytest # for running tests while building
Requirement already satisfied: nose in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages
Requirement already satisfied: pytest in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages
Requirement already satisfied: six>=1.10.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: attrs>=17.4.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: setuptools in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: funcsigs; python_version < "3.0" in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: py>=1.5.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: more-itertools>=4.0.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
Requirement already satisfied: pluggy<0.7,>=0.5 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pytest)
make[2]: Leaving directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make install # This will double -D_GNU_SOURCE, but that is ok for now.
make[2]: Entering directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make -C /home/jung/Tools/FALCON-integrate/DAZZ_DB all
make -C /home/jung/Tools/FALCON-integrate/DAMASKER all
make -C /home/jung/Tools/FALCON-integrate/DEXTRACTOR all
cd /home/jung/Tools/FALCON-integrate/pypeFLOW; pip uninstall -v .; pip install -v --user --edit .

> #TODO: copy vs. symlink?
make -C /home/jung/Tools/FALCON-integrate/nim-falcon/src -j1 all
ln -sf /home/jung/Tools/FALCON-integrate/git-sym/git-sym /home/jung/Tools/FALCON-integrate/fc_env/bin/git-sym
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DEXTRACTOR'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DEXTRACTOR'
PREFIX=/home/jung/Tools/FALCON-integrate/fc_env make -C /home/jung/Tools/FALCON-integrate/DEXTRACTOR symlink
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DEXTRACTOR'
ln -sf /home/jung/Tools/FALCON-integrate/DEXTRACTOR/dexta /home/jung/Tools/FALCON-integrate/DEXTRACTOR/undexta /home/jung/Tools/FALCON-integrate/fc_env/bin
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DAMASKER'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DAMASKER'
PREFIX=/home/jung/Tools/FALCON-integrate/fc_env make -C /home/jung/Tools/FALCON-integrate/DAMASKER symlink
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DAMASKER'
ln -sf /home/jung/Tools/FALCON-integrate/DAMASKER/datander /home/jung/Tools/FALCON-integrate/DAMASKER/TANmask /home/jung/Tools/FALCON-integrate/DAMASKER/REPmask /home/jung/Tools/FALCON-integrate/DAMASKER/HPC.TANmask /home/jung/Tools/FALCON-integrate/DAMASKER/HPC.REPmask /home/jung/Tools/FALCON-integrate/fc_env/bin
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DAMASKER'
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DEXTRACTOR'
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DAZZ_DB'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DAZZ_DB'
PREFIX=/home/jung/Tools/FALCON-integrate/fc_env make -C /home/jung/Tools/FALCON-integrate/DAZZ_DB symlink
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DAZZ_DB'
ln -sf /home/jung/Tools/FALCON-integrate/DAZZ_DB/fasta2DB /home/jung/Tools/FALCON-integrate/DAZZ_DB/DB2fasta /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBsplit /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBdust /home/jung/Tools/FALCON-integrate/DAZZ_DB/Catrack /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBshow /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBstats /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBrm /home/jung/Tools/FALCON-integrate/DAZZ_DB/simulator /home/jung/Tools/FALCON-integrate/DAZZ_DB/fasta2DAM /home/jung/Tools/FALCON-integrate/DAZZ_DB/DAM2fasta /home/jung/Tools/FALCON-integrate/DAZZ_DB/DBdump /home/jung/Tools/FALCON-integrate/DAZZ_DB/rangen /home/jung/Tools/FALCON-integrate/fc_env/bin
ln -sf /home/jung/Tools/FALCON-integrate/DAZZ_DB/libdazzdb.a /home/jung/Tools/FALCON-integrate/fc_env/lib
ln -sf /home/jung/Tools/FALCON-integrate/DAZZ_DB/DB.h /home/jung/Tools/FALCON-integrate/DAZZ_DB/QV.h /home/jung/Tools/FALCON-integrate/fc_env/include
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DAZZ_DB'
make -C /home/jung/Tools/FALCON-integrate/DALIGNER all
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/nim-falcon/src'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/nim-falcon/src'
rsync /home/jung/Tools/FALCON-integrate/nim-falcon/src/*.exe /home/jung/Tools/FALCON-integrate/fc_env/bin/
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DALIGNER'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DALIGNER'
PREFIX=/home/jung/Tools/FALCON-integrate/fc_env make -C /home/jung/Tools/FALCON-integrate/DALIGNER symlink
make[3]: Entering directory `/home/jung/Tools/FALCON-integrate/DALIGNER'
ln -sf /home/jung/Tools/FALCON-integrate/DALIGNER/daligner /home/jung/Tools/FALCON-integrate/DALIGNER/HPC.daligner /home/jung/Tools/FALCON-integrate/DALIGNER/LAsort /home/jung/Tools/FALCON-integrate/DALIGNER/LAmerge /home/jung/Tools/FALCON-integrate/DALIGNER/LAsplit /home/jung/Tools/FALCON-integrate/DALIGNER/LAcat /home/jung/Tools/FALCON-integrate/DALIGNER/LAshow /home/jung/Tools/FALCON-integrate/DALIGNER/LAdump /home/jung/Tools/FALCON-integrate/DALIGNER/LAcheck /home/jung/Tools/FALCON-integrate/DALIGNER/LAindex /home/jung/Tools/FALCON-integrate/DALIGNER/daligner_p /home/jung/Tools/FALCON-integrate/DALIGNER/LA4Falcon /home/jung/Tools/FALCON-integrate/DALIGNER/LA4Ice /home/jung/Tools/FALCON-integrate/DALIGNER/DB2Falcon /home/jung/Tools/FALCON-integrate/fc_env/bin
make[3]: Leaving directory `/home/jung/Tools/FALCON-integrate/DALIGNER'
Obtaining file:///home/jung/Tools/FALCON-integrate/pypeFLOW
  Running setup.py (path:/home/jung/Tools/FALCON-integrate/pypeFLOW/setup.py) egg_info for package from file:///home/jung/Tools/FALCON-integrate/pypeFLOW
    Running command python setup.py egg_info
    /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
  Source in /home/jung/Tools/FALCON-integrate/pypeFLOW has version 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef, which satisfies requirement pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef from file:///home/jung/Tools/FALCON-integrate/pypeFLOW
Requirement already satisfied: networkx<=1.11,>=1.7 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef)
Requirement already satisfied: future>=0.16.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef)
Requirement already satisfied: decorator>=3.4.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from networkx<=1.11,>=1.7->pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef)
Installing collected packages: pypeflow
  Found existing installation: pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    Uninstalling pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef:
      Removing file or directory /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
      Removing pth entries from /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /home/jung/Tools/FALCON-integrate/pypeFLOW
      Successfully uninstalled pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
  Running setup.py develop for pypeflow
    Running command /home/jung/.pyenv/versions/2.7.9/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/jung/Tools/FALCON-integrate/pypeFLOW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=
    /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running develop
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link (link to .)
    Adding pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef to easy-install.pth file
    Installing pwatcher-pypeflow-example script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing heartbeat-wrapper script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing pwatcher-main script to /home/jung/Tools/FALCON-integrate/fc_env/bin
> Installed /home/jung/Tools/FALCON-integrate/pypeFLOW
Successfully installed pypeflow
Cleaning up...
cd /home/jung/Tools/FALCON-integrate/FALCON; pip uninstall -v .; pip install -v --user --edit .
Obtaining file:///home/jung/Tools/FALCON-integrate/FALCON
  Running setup.py (path:/home/jung/Tools/FALCON-integrate/FALCON/setup.py) egg_info for package from file:///home/jung/Tools/FALCON-integrate/FALCON
    Running command python setup.py egg_info
    /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382
    ' to '1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382'
      normalized_version,
    running egg_info
    writing requirements to falcon_kit.egg-info/requires.txt
    writing falcon_kit.egg-info/PKG-INFO
    writing top-level names to falcon_kit.egg-info/top_level.txt
    writing dependency_links to falcon_kit.egg-info/dependency_links.txt
    writing entry points to falcon_kit.egg-info/entry_points.txt
    reading manifest file 'falcon_kit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'falcon_kit.egg-info/SOURCES.txt'
  Source in /home/jung/Tools/FALCON-integrate/FALCON has version 1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382, which satisfies requirement falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382 from file:///home/jung/Tools/FALCON-integrate/FALCON
Requirement already satisfied: networkx<=1.11,>=1.7 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382)
Requirement already satisfied: msgpack in /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages (from falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382)
Requirement already satisfied: future>=0.16.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382)
Requirement already satisfied: pypeFLOW>=2.0.0 in /home/jung/Tools/FALCON-integrate/pypeFLOW (from falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382)
Requirement already satisfied: decorator>=3.4.0 in /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages (from networkx<=1.11,>=1.7->falcon-kit==1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382)
Installing collected packages: falcon-kit
  Found existing installation: falcon-kit 1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382
    Uninstalling falcon-kit-1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382:
      Removing file or directory /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon-kit.egg-link
      Removing pth entries from /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /home/jung/Tools/FALCON-integrate/FALCON
      Successfully uninstalled falcon-kit-1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382
  Running setup.py develop for falcon-kit
    Running command /home/jung/.pyenv/versions/2.7.9/bin/python2.7 -c "import setuptools, tokenize;__file__='/home/jung/Tools/FALCON-integrate/FALCON/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=
    /home/jung/.pyenv/versions/2.7.9/lib/python2.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382
    ' to '1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382'
      normalized_version,
    running develop
    running egg_info
    writing requirements to falcon_kit.egg-info/requires.txt
    writing falcon_kit.egg-info/PKG-INFO
    writing top-level names to falcon_kit.egg-info/top_level.txt
    writing dependency_links to falcon_kit.egg-info/dependency_links.txt
    writing entry points to falcon_kit.egg-info/entry_points.txt
    reading manifest file 'falcon_kit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'falcon_kit.egg-info/SOURCES.txt'
    running build_ext
    copying build/lib.linux-x86_64-2.7/ext_falcon.so ->
    Creating /home/jung/Tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon-kit.egg-link (link to .)
    Adding falcon-kit 1.0+git.c1e0d45f1b847f572cd9834576154ae44bbd7382 to easy-install.pth file
    Installing fc_fetch_reads script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_pr_ctg_track script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_actg_coordinate script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_fasta2fasta script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_run.py script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_ctg_link_analysis script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_ovlp_to_graph script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_gen_gfa_v1 script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_ovlp_filter script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_get_read_ctg_map script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_run script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_contig_annotate script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_graph_to_utgs script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_run1 script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_ovlp_stats script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_consensus script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_rr_ctg_track script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_calc_cutoff script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing falcon-task script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_graph_to_contig script to /home/jung/Tools/FALCON-integrate/fc_env/bin
    Installing fc_dedup_a_tigs script to /home/jung/Tools/FALCON-integrate/fc_env/bin

> Installed /home/jung/Tools/FALCON-integrate/FALCON
Successfully installed falcon-kit
Cleaning up...
make[2]: Leaving directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make check
make[2]: Entering directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
python -c 'import pypeflow.simple_pwatcher_bridge; print pypeflow.simple_pwatcher_bridge'
<module 'pypeflow.simple_pwatcher_bridge' from '/home/jung/Tools/FALCON-integrate/pypeFLOW/pypeflow/simple_pwatcher_bridge.pyc'>
python -c 'import falcon_kit; print falcon_kit.falcon'
<CDLL '/home/jung/Tools/FALCON-integrate/FALCON/ext_falcon.so', handle 18fd1d0 at 2ac6464b18d0>
make[2]: Leaving directory `/home/jung/Tools/FALCON-integrate/FALCON-make'
make[1]: Leaving directory `/home/jung/Tools/FALCON-integrate/FALCON-make'

**Comment by pb-cdunn** [comment]
The `activate` file will exist only if you set up your own `virtualenv`. You'll have to google that. `PYTHONUSERBASE` is another option.
