### ISSUE TITLE
Error: execution of an external compiler program

### ISSUE THREAD

**Issue by AlexYang01** [PacificBiosciences/FALCON-integrate#172]
Hi,
When I installed FALCON according to "The easy way (in a new directory)", I got a problem as follow:

Error: execution of an external compiler program 'gcc -c  -w -pthread -O3 -fno-strict-aliasing  -I/software/nim/nim-0.18.0/lib -o /software/Falcon/FALCON-integrate/nim-falcon/src/nimcache/stdlib_system.o /software/Falcon/FALCON-integrate/nim-falcon/src/nimcache/stdlib_system.c' failed with exit code: 1

Could you please help me ?

Many thanks!

**Comment by pb-cdunn** [comment]
You need **gcc**, and maybe a fairly recent version.
