### ISSUE TITLE
Number of CPUs in the slurm system

### ISSUE THREAD

**Issue by marcelauliano** [PacificBiosciences/FALCON-integrate#173]
Hey guys, I'm assembling a mammal genome (3.5Gb) with the FALCON-integrate release from a month ago.

I have configure the cfg file for the slurm system I use. Then I found out that the cluster slurm system is asking for at least 22 CPUs for a job to run - even though I have set the script to use 4 CPUs and 64Gb of memory for each job (when I tried 40G it died out of memory). I set it to run 70 concurrent jobs.

Bellow I post my cfg file and the message I get from the cluster when I do 'scontrol show jobid'. From the 4 line up in the result of the 'scontrol show jobid' it says the cluster is asking for MinCPUsNode=22 for a job to run. I wonder why.

Is there any parameter missing in my cfg file, or do you think this is a cluster management issue? 

Thanks  a lot for your help! (It would be nice to sort this out, as I have many available nodes that are smaller than 22, but would be very suitable to run a 4 CPUs daligner job, as I wished to do).

Thats my cfg file:
```
### [General]
input_fofn = input.fofn

input_type = raw
openending = True

length_cutoff = -1
length_cutoff_pr = 13000
genome_size = 3500000000
seed_coverage = 30.0

job_type = SLURM
#job_queue = srun
sge_option_da = --cpus-per-task 4 --mem 64g --time 4:00:00 -o sge_option_da.out --mail-type=all --mail-user=bla@gmail.com -J da -D /outputfolder
sge_option_la = --cpus-per-task 20 --mem 71g --time 10:00:00 -o sge_option_la.out --mail-type=all --mail-user=bla@gmail.com -J la -D /outputfolder
sge_option_pda = --cpus-per-task 6 --mem 71g --time 10:00:00 -o sge_option_pda.out --mail-type=all --mail-user=bla@gmail.com -J pda -D /outputfolder
sge_option_pla = --cpus-per-task 16 --mem 71g --time 10:00:00 -o sge_option_pla.out --mail-type=all --mail-user=bla@gmail.com -J pla -D /outputfolder 
sge_option_fc = --cpus-per-task 24 --mem 71g --time 10:00:00 -o sge_option_fc.out --mail-type=all --mail-user=bla@gmail.com -J fc -D /outputfolder
sge_option_cns = --cpus-per-task 8 --mem 71g --time 10:00:00 -o sge_option_cns.out --mail-type=all --mail-user=bla@gmail.com -J cns -D /outputfolder

pa_concurrent_jobs = 70
cns_concurrent_jobs = 60
ovlp_concurrent_jobs = 60
pa_HPCdaligner_option =  -v -dal128 -t16 -M32 -e.70 -l4800 -s100 -k18 -h480 -w8 -H15000
ovlp_HPCdaligner_option = -v -dal128 -t32 -M32 -h1024 -e.96 -l2400 -s100 -k24 -H15000
pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -s400
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 2 --max_n_read 200 --n_core 8
falcon_sense_skip_contained = True
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 2 --n_core 12**
```

And the slurm message I get as I check the submitted jobs is this:
```
   JobId=1839319 Name=da
   UserId=x(266187) GroupId=x(10099)
   Priority=1563 Nice=0 Account=x QOS=normal
   JobState=PENDING Reason=Resources Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=04:00:00 TimeMin=N/A
   SubmitTime=2018-04-11T11:56:01 EligibleTime=2018-04-11T11:56:01
   StartTime=2018-04-14T18:47:13 EndTime=Unknown
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   Partition=small AllocNode:Sid=x:27611
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=(null)
   NumNodes=1 NumCPUs=4 CPUs/Task=4 ReqB:S:C:T=0:0:*:*
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=0
   MinCPUsNode=22 MinMemoryNode=64G MinTmpDiskNode=0
   Features=(null) Gres=(null) Reservation=(null)
   Shared=0 Contiguous=0 Licenses=(null) Network=(null)
   Command=(null)
```

**Comment by pb-cdunn** [comment]
Marcela, this is a bit old, but if you're still having problems with Slurm, let's discuss in Slack. Then I'll try to update the Wiki later. We definitely want to support Slurm.

**Comment by zrlewis** [comment]
I am also having trouble getting `FALCON-integrate` running on SLURM. @pb-cdunn, could you point me to the Slack channel or any other resources? I haven't been able to come up with a working `.cfg` file yet for the test datasets.

**Comment by pb-cdunn** [comment]
FALCON-integrate is deprecated because we now longer push updates of Falcon to GitHub.

* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries
