### ISSUE TITLE
Environment settings error in the wiki

### ISSUE THREAD

**Issue by lorenzoditucci** [PacificBiosciences/FALCON-integrate#174]
Hi,

I think there is an error in the wiki when setting the environment variables  PYTHONUSERBASE and PATH. I am talking about the section [Dependencies](https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation)

In particular, it is written: 

```
PATH
Before running tests, you need to add the new bin to your PATH. E.g.

export PYTHONUSERBASE=$(python -c 'import site; print site.userbase')
export PATH=${PYTHONUSERBASE}/bin
```

The first error is in the command:

`export PYTHONUSERBASE=$(python -c 'import site; print site.userbase')
`

In fact, in Python 2.7.9 the field is not userbase, it is USER_BASE changin the command to:

`export PYTHONUSERBASE=$(python -c 'import site; print site.USER_BASE')
`

The second issue is when setting the path, in fact I think that for completeness the command shoul be:
`export PATH=${PYTHONUSERBASE}/bin:$PATH`

thanks

**Comment by pb-cdunn** [comment]
You're right on both counts. Thank you.
