### ISSUE TITLE
FALCON install problem

### ISSUE THREAD

**Issue by kramergj** [PacificBiosciences/FALCON-integrate#175]
Hi there,
I am having difficulty getting FALCON to install. Apologies if my questions are obvious, as I am somewhat new to thing, but I will appreciate any help you can give!

Here is what I have tried: Install not in a virtualenv (computer running python 2.7.12)
```
export GIT_SYM_CACHE_DIR=~/.git-sym-cache
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout develop  # or whatever version you want
git submodule update --init --recursive # Note: You must do this yourself! No longer via `make init`.
make init
source env.sh
make config-edit-user
make -j all
```

However I am met with the error: when I try `sudo make -j all`
```
make -C ./FALCON-make/ all
make[1]: Entering directory '/home/FALCON-integrate/FALCON-make'
Error: FALCON_PREFIX is not set
makefile:22: recipe for target 'checklist' failed
make[1]: *** [checklist] Error 1
make[1]: Leaving directory '/home/FALCON-integrate/FALCON-make'
makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
```

I have also tried setting this up in a virtual environment using anaconda and python 2.7.9 and have gotten a similar error  after `make -j all`
```
Installed /home/nodwell/FALCON-integrate/pypeFLOW
Successfully installed decorator-4.3.0 future-0.16.0 networkx-1.11 pypeflow
Cleaning up...
make[2]: Leaving directory '/home/FALCON-integrate/FALCON-make'
makefile:17: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/FALCON-integrate/FALCON-make'
makefile:18: recipe for target 'all' failed
make: *** [all] Error 2
```
Thank you so much in advance for any suggestions!

**Comment by pb-cdunn** [comment]
`Error: FALCON_PREFIX is not set`

What is in your `env.sh`? Mine looks like this:
```
$ cat env.sh
FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib
```
where `$(pwd)` is  the directory of `FALCON-integrate`. `FALCON_PREFIX` is definitely set for me. Your `sudo` command might be run from a different shell than your `source env.sh`.

**Comment by kramergj** [comment]
Thank you for the thought!  It seems to return the same as what you have posted, so I am not sure what is going on.  

```
$ cat env.sh
FALCON_WORKSPACE=$(pwd)
PYTHONUSERBASE=$(pwd)/fc_env
FALCON_PREFIX=${PYTHONUSERBASE}
PATH=${PYTHONUSERBASE}/bin:${FALCON_PREFIX}/bin:${PATH}
export PYTHONUSERBASE
export FALCON_WORKSPACE
export FALCON_PREFIX
export PATH
mkdir -p ${FALCON_PREFIX}/include
mkdir -p ${FALCON_PREFIX}/bin
mkdir -p ${FALCON_PREFIX}/lib
```
Also, if I open the config.mk in the FALCON-make folder, it shows on line 4
`FALCON_PREFIX=/home/mycomputer/Assembly_Programs/Falcon/FALCON-integrate/fc_env`

**Comment by pb-cdunn** [comment]
It's not something I can help with from here. But when you find the problem, please let us know. Maybe we can help others to avoid it in the future.
