### ISSUE TITLE
Where is falcon-unzip?

### ISSUE THREAD

**Issue by yangwu91** [PacificBiosciences/FALCON-integrate#177]
Hi,
It looks like falcon-unzip was not integrated since Version 1.8.6, and the latest FALCON-integrate results couldn't be fed to falcon-unzip. If I want to use falcon-unzip, do I have to install FALCON-intergrate V1.8.5? Thanks!

**Comment by cgjosephlee** [comment]
http://pb-falcon.readthedocs.io/en/latest/quick_start.html

This bundle also carries a prebuilt falcon distribution, but I guess it's not the latest (v2.1.4).

**Comment by pb-cdunn** [comment]
https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

> If I want to use falcon-unzip, do I have to install FALCON-intergrate V1.8.5?

Not anymore. But I *highly* recommend trying **FALCON-examples**:
* https://github.com/pb-cdunn/FALCON-examples

```sh
cd FALCON-examples
cd run/synth0
git-sym .
make
cd ../greg200k-sv2
# edit *.cfg
make falcon
make unzip
```
Fast test-cases are helpful in solving integration problems.
