### ISSUE TITLE
Different output of FALCON-integrate

### ISSUE THREAD

**Issue by lyx8162236** [PacificBiosciences/FALCON-integrate#179]
Hi FALCON developer,

I have being used FALCON-integrate to assemble my PacBio data for a while. I got different kinds of output files when I run different version of FALCON-integrate. Someone in my lab has installed and run FALCON before, so I firstly tried to run his version of FALCON-integrate. Then I install the FALCON-integrate by myself and got the different kinds of output files. Both of these two jobs are completed and successfully. The configure file and the input file and the same, the only difference is the bash script. 

I listed the two different scripts and output files below.
Script 1:
#!/bin/bash
#SBATCH --partition=kamiak
#SBATCH --job-name=falcon_12
#SBATCH --output=raw.test.falcon.o
#SBATCH --error=raw.test.falcon.e
#SBATCH --time=3-00:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=20
#SBATCH --ntasks-per-node=1
#SBATCH --mem=256000
#SBATCH --mail-type=ALL
#SBATCH --mail-user=yuxiang.li@wsu.edu

cd /data/chen/software/FALCON-integrate
module load git/2.6.3
git checkout master
make init
source env.sh
make config-edit-user
make -j all
cd FALCON-make/
bash config-edit-user.sh
export PYTHONUSERBASE=$(python -c 'import site; print site.USER_BASE')
export PATH=$PATH:{PYTHONUSERBASE}/bin 
cd /data/chen/yuxiang.li/PacBio/test2.0	
fc_run.py fc_run.cfg

Script 2: 
#!/bin/bash
#SBATCH --partition=kamiak
#SBATCH --job-name=falcon_12
#SBATCH --output=raw.test.falcon.o
#SBATCH --error=raw.test.falcon.e
#SBATCH --time=3-00:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=20
#SBATCH --ntasks-per-node=1
#SBATCH --mem=256000
#SBATCH --mail-type=ALL
#SBATCH --mail-user=yuxiang.li@wsu.edu

cd /data/cahnrs/xchen/yuxiang.li/yuxiang/illumina/12_FALCON/FALCON-integrate/
module load git/2.6.3
git checkout master
source env.sh
cd FALCON-make/
bash config-edit-user.sh
export PYTHONUSERBASE=$(python -c 'import site; print site.USER_BASE')
export PATH=$PATH:{PYTHONUSERBASE}/bin
cd /data/chen/yuxiang.li/PacBio/12.0
fc_run.py fc_run.cfg

Output1 in 0-rawreads folder:

cns-scatter       job_0065  job_00cc  job_0133  job_019a  job_0201  job_0268
daligner-scatter  job_0066  job_00cd  job_0134  job_019b  job_0202  job_0269
job_0000          job_0067  job_00ce  job_0135  job_019c  job_0203  job_026a
job_0001          job_0068  job_00cf  job_0136  job_019d  job_0204  job_026b
job_0002          job_0069  job_00d0  job_0137  job_019e  job_0205  job_026c
job_0003          job_006a  job_00d1  job_0138  job_019f  job_0206  job_026d
job_0004          job_006b  job_00d2  job_0139  job_01a0  job_0207  job_026e
job_0005          job_006c  job_00d3  job_013a  job_01a1  job_0208  job_026f
job_0006          job_006d  job_00d4  job_013b  job_01a2  job_0209  job_0270
job_0007          job_006e  job_00d5  job_013c  job_01a3  job_020a  job_0271
job_0008          job_006f  job_00d6  job_013d  job_01a4  job_020b  job_0272
job_0009          job_0070  job_00d7  job_013e  job_01a5  job_020c  job_0273
job_000a          job_0071  job_00d8  job_013f  job_01a6  job_020d  job_0274
job_000b          job_0072  job_00d9  job_0140  job_01a7  job_020e  job_0275
job_000c          job_0073  job_00da  job_0141  job_01a8  job_020f  length_cutoff
job_000d          job_0074  job_00db  job_0142  job_01a9  job_0210  m_00001
job_000e          job_0075  job_00dc  job_0143  job_01aa  job_0211  m_00002
job_000f          job_0076  job_00dd  job_0144  job_01ab  job_0212  m_00003
job_0010          job_0077  job_00de  job_0145  job_01ac  job_0213  m_00004
job_0011          job_0078  job_00df  job_0146  job_01ad  job_0214  m_00005
job_0012          job_0079  job_00e0  job_0147  job_01ae  job_0215  m_00006
job_0013          job_007a  job_00e1  job_0148  job_01af  job_0216  m_00007
job_0014          job_007b  job_00e2  job_0149  job_01b0  job_0217  m_00008
job_0015          job_007c  job_00e3  job_014a  job_01b1  job_0218  m_00009
job_0016          job_007d  job_00e4  job_014b  job_01b2  job_0219  m_00010
job_0017          job_007e  job_00e5  job_014c  job_01b3  job_021a  m_00011
job_0018          job_007f  job_00e6  job_014d  job_01b4  job_021b  m_00012
job_0019          job_0080  job_00e7  job_014e  job_01b5  job_021c  m_00013
job_001a          job_0081  job_00e8  job_014f  job_01b6  job_021d  m_00014
job_001b          job_0082  job_00e9  job_0150  job_01b7  job_021e  m_00015
job_001c          job_0083  job_00ea  job_0151  job_01b8  job_021f  m_00016
job_001d          job_0084  job_00eb  job_0152  job_01b9  job_0220  m_00017
job_001e          job_0085  job_00ec  job_0153  job_01ba  job_0221  m_00018
job_001f          job_0086  job_00ed  job_0154  job_01bb  job_0222  m_00019
job_0020          job_0087  job_00ee  job_0155  job_01bc  job_0223  m_00020
job_0021          job_0088  job_00ef  job_0156  job_01bd  job_0224  m_00021
job_0022          job_0089  job_00f0  job_0157  job_01be  job_0225  m_00022
job_0023          job_008a  job_00f1  job_0158  job_01bf  job_0226  m_00023
job_0024          job_008b  job_00f2  job_0159  job_01c0  job_0227  m_00024
job_0025          job_008c  job_00f3  job_015a  job_01c1  job_0228  m_00025
job_0026          job_008d  job_00f4  job_015b  job_01c2  job_0229  m_00026
job_0027          job_008e  job_00f5  job_015c  job_01c3  job_022a  m_00027
job_0028          job_008f  job_00f6  job_015d  job_01c4  job_022b  m_00028
job_0029          job_0090  job_00f7  job_015e  job_01c5  job_022c  m_00029
job_002a          job_0091  job_00f8  job_015f  job_01c6  job_022d  m_00030
job_002b          job_0092  job_00f9  job_0160  job_01c7  job_022e  m_00031
job_002c          job_0093  job_00fa  job_0161  job_01c8  job_022f  m_00032
job_002d          job_0094  job_00fb  job_0162  job_01c9  job_0230  m_00033
job_002e          job_0095  job_00fc  job_0163  job_01ca  job_0231  m_00034
job_002f          job_0096  job_00fd  job_0164  job_01cb  job_0232  m_00035
job_0030          job_0097  job_00fe  job_0165  job_01cc  job_0233  m_00036
job_0031          job_0098  job_00ff  job_0166  job_01cd  job_0234  m_00037
job_0032          job_0099  job_0100  job_0167  job_01ce  job_0235  m_00038
job_0033          job_009a  job_0101  job_0168  job_01cf  job_0236  m_00039
job_0034          job_009b  job_0102  job_0169  job_01d0  job_0237  m_00040
job_0035          job_009c  job_0103  job_016a  job_01d1  job_0238  m_00041
job_0036          job_009d  job_0104  job_016b  job_01d2  job_0239  m_00042
job_0037          job_009e  job_0105  job_016c  job_01d3  job_023a  m_00043
job_0038          job_009f  job_0106  job_016d  job_01d4  job_023b  m_00044
job_0039          job_00a0  job_0107  job_016e  job_01d5  job_023c  m_00045
job_003a          job_00a1  job_0108  job_016f  job_01d6  job_023d  m_00046
job_003b          job_00a2  job_0109  job_0170  job_01d7  job_023e  m_00047
job_003c          job_00a3  job_010a  job_0171  job_01d8  job_023f  m_00048
job_003d          job_00a4  job_010b  job_0172  job_01d9  job_0240  m_00049
job_003e          job_00a5  job_010c  job_0173  job_01da  job_0241  m_00050
job_003f          job_00a6  job_010d  job_0174  job_01db  job_0242  m_00051
job_0040          job_00a7  job_010e  job_0175  job_01dc  job_0243  m_00052
job_0041          job_00a8  job_010f  job_0176  job_01dd  job_0244  m_00053
job_0042          job_00a9  job_0110  job_0177  job_01de  job_0245  m_00054
job_0043          job_00aa  job_0111  job_0178  job_01df  job_0246  m_00055
job_0044          job_00ab  job_0112  job_0179  job_01e0  job_0247  m_00056
job_0045          job_00ac  job_0113  job_017a  job_01e1  job_0248  m_00057
job_0046          job_00ad  job_0114  job_017b  job_01e2  job_0249  m_00058
job_0047          job_00ae  job_0115  job_017c  job_01e3  job_024a  m_00059
job_0048          job_00af  job_0116  job_017d  job_01e4  job_024b  m_00060
job_0049          job_00b0  job_0117  job_017e  job_01e5  job_024c  m_00061
job_004a          job_00b1  job_0118  job_017f  job_01e6  job_024d  m_00062
job_004b          job_00b2  job_0119  job_0180  job_01e7  job_024e  m_00063
job_004c          job_00b3  job_011a  job_0181  job_01e8  job_024f  m_00064
job_004d          job_00b4  job_011b  job_0182  job_01e9  job_0250  m_00065
job_004e          job_00b5  job_011c  job_0183  job_01ea  job_0251  m_00066
job_004f          job_00b6  job_011d  job_0184  job_01eb  job_0252  m_00067
job_0050          job_00b7  job_011e  job_0185  job_01ec  job_0253  m_00068
job_0051          job_00b8  job_011f  job_0186  job_01ed  job_0254  m_00069
job_0052          job_00b9  job_0120  job_0187  job_01ee  job_0255  merge-gather
job_0053          job_00ba  job_0121  job_0188  job_01ef  job_0256  merge-scatter
job_0054          job_00bb  job_0122  job_0189  job_01f0  job_0257  preads
job_0055          job_00bc  job_0123  job_018a  job_01f1  job_0258  prepare_rdb.sh
job_0056          job_00bd  job_0124  job_018b  job_01f2  job_0259  pwatcher.dir
job_0057          job_00be  job_0125  job_018c  job_01f3  job_025a  raw-fofn-abs
job_0058          job_00bf  job_0126  job_018d  job_01f4  job_025b  raw-gather
job_0059          job_00c0  job_0127  job_018e  job_01f5  job_025c  raw_reads.db
job_005a          job_00c1  job_0128  job_018f  job_01f6  job_025d  rdb_build_done
job_005b          job_00c2  job_0129  job_0190  job_01f7  job_025e  report
job_005c          job_00c3  job_012a  job_0191  job_01f8  job_025f  run_jobs.sh
job_005d          job_00c4  job_012b  job_0192  job_01f9  job_0260  run.sh
job_005e          job_00c5  job_012c  job_0193  job_01fa  job_0261  run.sh.done
job_005f          job_00c6  job_012d  job_0194  job_01fb  job_0262  task.json
job_0060          job_00c7  job_012e  job_0195  job_01fc  job_0263  task.sh
job_0061          job_00c8  job_012f  job_0196  job_01fd  job_0264
job_0062          job_00c9  job_0130  job_0197  job_01fe  job_0265
job_0063          job_00ca  job_0131  job_0198  job_01ff  job_0266
job_0064          job_00cb  job_0132  job_0199  job_0200  job_0267

Output2 in 0-rawreads folder:

build       daligner-chunks    las-gather          las-merge-split  tan-gathered
cns-chunks  daligner-combine   las-merge-chunks    preads           tan-runs
cns-gather  daligner-gathered  las-merge-combine   report           tan-split
cns-runs    daligner-runs      las-merge-gathered  tan-chunks
cns-split   daligner-split     las-merge-runs      tan-combine

Can you help me figure out why I got different results, much appreciated.

Yuxiang

**Comment by pb-cdunn** [comment]
We sometimes change the directory structure. (In this case, it's because we are attempting to support a wider variety of workflow drivers.) Technically, we should bump the major version number in these cases, but we have only been bumping the minor.

**Comment by lyx8162236** [comment]
Thanks for your answer. But the output of my directory structure is not compatible with falcon-unzip, so how should I solve this problem?

**Comment by pb-cdunn** [comment]
For a given tarball, you have consistent versions of code. You're fine as long as you don't mix releases.
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

(Btw, we will be in Bioconda soon, which hopefully will make this easier.)

In the past, I used FALCON-integrate to indicate consistent versions, but because of PacBio management decisions, we no longer have the latest code in GitHub, so this integration package has lost its value. I only use it for the FALCON-examples testdata now.
