### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by phpeters** [PacificBiosciences/FALCON-integrate#18]
Hej,

I have some problems installing the falcon on a cluster, where I don't have any sudo rights. I load python2.7 and as compiler I can load  intel/14.0.2, 15.0.2 or 16.0.0

The first error appears when I do:
make init
I get an usage error for
git submodule update --init --depth=1 virtualenv

The major error I get (using any of the intel compilers) is for  the install command:
make -j install
[....]
Using /home/Data/programs/FALCON-integrate/FALCON/.eggs/decorator-4.0.4-py2.7.egg
Finished processing dependencies for falcon-kit==0.4.0
python -c 'import falcon_kit; print falcon_kit.falcon'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/Data/programs/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/**init**.py", line 39, in <module>
    from .falcon_kit import *
  File "/home/Data/programs/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/falcon_kit.py", line 45, in <module>
    from . import ext_falcon
ImportError: /home/Data/programs/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/ext_falcon.so: undefined symbol: _intel_fast_memset
make[1]: **\* [install] Error 1
make[1]: Leaving directory `/home/Data/programs/FALCON-integrate/FALCON-make'
make: **\* [install] Error 2

Do you have any hint how to circumvent this error?
Thanks in advance and best regards,
Philipp

**Comment by pb-cdunn** [comment]
> I get an usage error for
>     git submodule update --init --depth=1 virtualenv

You probably have an old version of **git**. Drop `--depth=1`.

```
ImportError: /home/Data/programs/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/ext_falcon.so: undefined symbol: _intel_fast_memset
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/Data/programs/FALCON-integrate/FALCON-make'
make: *** [install] Error 2
```

> Do you have any hint how to circumvent this error?

I think you need to load the intel libraries:
- libirc
- libimf
  That could be done at runtime (e.g. via LD_LIBRARY_PATH), or in some other way.

You are free to modify `FALCON-make` or to use something completely different for integration. It's hard for us to debug your environment.
