### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by ramayyala** [PacificBiosciences/FALCON-integrate#180]
So I am running into a bit of an issue when trying to install Falcon. The error is below. 
Every command that i typed before make -j all worked:
export GIT_SYM_CACHE_DIR=~/.git-sym-cache # to speed things up
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout develop  # or whatever version you want
git submodule update --init --recursive # Note: You must do this yourself! No longer via `make init`.
make init
source env.sh
make config-edit-user

However, whenever i tried make -j all, this error came up. It says syntax error, but I don't seem to see where the syntax error is. Is it the commands I was typing or something else? 

make -C ./FALCON-make/ all
make[1]: Entering directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
mkdir -p /u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/bin
which python
/usr/bin/python
echo "PYTHONUSERBASE=/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env"
PYTHONUSERBASE=/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/lib/python2.6/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
Traceback (most recent call last):
  File "/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/lib/python2.6/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/lib/python2.6/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/u/home/r/ramayyal/Tools/FALCON-integrate/fc_env/lib/python2.6/site-packages/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax
make[2]: *** [install-pip] Error 1
make[2]: Leaving directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/u/home/r/ramayyal/Tools/FALCON-integrate/FALCON-make'
make: *** [all] Error 2

**Comment by MajoroMask** [comment]
Try using python 2.7.9 as instructed. At least you won't get caught at very start of this awful installation >_<

**Comment by apredeus** [comment]
This installation is really something else. I don't think I've been this frustrated trying to work things out in years.

**Comment by pb-cdunn** [comment]
`python2.6` -- not supported. You need `python2.7`.

But I don't think source-code is up-to-date here anyway. We no longer keep these GitHub repos up-to-date. To use Falcon, try a binary release: https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

Soon, we expect to release via bio-conda.
