### ISSUE TITLE
FALCON_PREFIX is not set

### ISSUE THREAD

**Issue by cahuparo** [PacificBiosciences/FALCON-integrate#181]
Hi, I am trying to install FALCON-integrate in my Mac but I encounter this error after entering the command:

`$ make -j all`

```
make -C ./FALCON-make/ all
Error: FALCON_PREFIX is not set
make[1]: *** [checklist] Error 1
make: *** [all] Error 2
```
Please, could you help me pass this error?

Thank you so much in advance, 

Camilo

**Comment by pb-cdunn** [comment]
You have to follow the full directions:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
* https://github.com/PacificBiosciences/FALCON-integrate/wiki

I think you've missed this part:
```
make init
source env.sh
make config-edit-user
```

**Comment by pb-cdunn** [comment]
But this is deprecated now anyway. We no longer push the latest code into GitHub, so installing from FALCON-integrate is no longer maintained. Instead, use the tarball.
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries
