### ISSUE TITLE
Falcon output files are not compatible with falcon-unzip

### ISSUE THREAD

**Issue by lyx8162236** [PacificBiosciences/FALCON-integrate#182]
The output of my falcon output files are in the different format compared with your website. The picture showed the output directory of 0-rawreads. I can still find the assembly in the 2-asm-falcon, also there is no error in the log file. 

But the problem is the output files is not compatible with following falcon-unzip. So how can I solve this problem.

Thank you 

Yuxiang
 
![image](https://user-images.githubusercontent.com/26955313/43533495-c70fe12c-9569-11e8-9486-23c901d73af3.png)

**Comment by pb-cdunn** [comment]
We no longer keep GitHub code up-to-date, so you need to use the tarball:
* https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

Then, you will have consistent versions of code.
