### ISSUE TITLE
need some explanation for the output folder

### ISSUE THREAD

**Issue by hollandorange** [PacificBiosciences/FALCON-integrate#184]
Thanks for your help with downloading the testing data.
I encounter more questions:
Question 1: My output folder structure is different from the one explained in Wiki, take `0-rawreads` folder for example. I am wondering where are the error corrected reads? (previously they are saved as `0-rawreads/preads/cns....*.fasta`, but now no fasta file in preads)
```
zhangyanju@thinkstation:~/software/FALCON-integrate/testdata/0-rawreads$ ls
build_rdb.sh  daligner-chunks                     las-gather          length_cutoff  rdb_build_done  task.json
cns-chunks    daligner-gathered                   las-merge-chunks    my.input.fofn  report          task.sh
cns-gather    daligner-intermediate-gathered-las  las-merge-gathered  preads         run_jobs.sh     template.sh
cns-runs      daligner-runs                       las-merge-runs      pwatcher.dir   run.sh          user_script.sh
cns-split     daligner-split                      las-merge-split     raw_reads.db   run.sh.done
```
Question 2: if I want to only perform error correction, do I only need to set the `target = pre-assembly`? Is this correct? or other parameters I should change?

Question 3: I followed the installation instruction for the developer. Which version did I installed? Is there a version number?
```
zhangyanju@thinkstation:~/software/FALCON-integrate$ git checkout 
M	DALIGNER
M	DAZZ_DB
M	DEXTRACTOR
M	FALCON-examples
M	pypeFLOW
```
Your branch is up-to-date with 'origin/develop'.

Your answer will be very appreciated.

**Comment by pb-cdunn** [comment]
1. See below.
2. I think that's right, though nobody has tried that in a while.
3. `git submodule --help` -- But unfortunately, this package is no longer maintained, so it's not likely to work. Please use a binary instead: https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries

Example of fasta files:
```
./0-rawreads/cns-runs/cns_00003/uow-00/consensus.cns_00003.fasta
./0-rawreads/cns-runs/cns_00001/uow-00/consensus.cns_00001.fasta
./0-rawreads/cns-runs/cns_00002/uow-00/consensus.cns_00002.fasta
./1-preads_ovl/db2falcon/preads4falcon.fasta
./2-asm-falcon/preads4falcon.fasta
./3-unzip/0-phasing/000000F/uow-00/proto/preads.fasta
./3-unzip/0-phasing/000000F/uow-00/proto/minced.fasta
./3-unzip/1-hasm/preads4falcon.fasta
./3-unzip/2-htigs/chunk_000000F/uow-000000F/aln_snp_hasm_ctg.fasta
./3-unzip/2-htigs/chunk_000000F/uow-000000F/regions.fasta
./4-quiver/cns-output/cns_p_ctg.fasta
./4-quiver/cns-output/cns_h_ctg.fasta
```
