### ISSUE TITLE
no preads generated when setting target=pre-assembly

### ISSUE THREAD

**Issue by hollandorange** [PacificBiosciences/FALCON-integrate#185]
I followed up the suggestion to install Falcon using the binary (release0.5,3/12/2018). when I set the cfg file parameter ```target=pre-assembly```, the program can run without errors, but I can not find the pre-assembled reads. The folders, such as 0-rawreads/pread and 0-rawreads/cns-runs are missing in the output. 

these are some of the final lines of the screen output

```
inputs={u'gathered': u'0-rawreads/cns-gather/gathered.json'},
outputs={u'preads_fofn': u'0-rawreads/preads/input_preads.fofn'})
[INFO]gen_task(python -m falcon_kit.mains.task_report_pre_assembly --config-fn={input.config} --length-cutoff-fn={input.length_cutoff} --raw-reads-db-fn={input.raw_reads_db} --preads-fofn-fn={input.preads_fofn} --pre-assembly-report-fn={output.pre_assembly_report}
inputs={u'length_cutoff': u'0-rawreads/length_cutoff', u'preads_fofn': u'0-rawreads/preads/input_preads.fofn', u'config': u'config.json', u'raw_reads_db': u'0-rawreads/raw_reads.db'},
outputs={u'pre_assembly_report': u'0-rawreads/report/pre_assembly_stats.json'})
[INFO]Quitting after stage-0 for "pre-assembly" target.
```
It seems the folders and files ```'0-rawreads/preads/input_preads.fofn'```,  ```'0-rawreads/cns-runs'```and ```'0-rawreads/report'``` are scheduled to be generated but I could not find them finally .
If I only change the parameter back to ```target=assembly``` (the rest of the cfg  and the input are the same), then I get both the preads and the assembly.

Did you forget to save the preads  when setting ```target=pre-assembly```? Could you  tell me what 's wrong?

Thanks

**Comment by pb-cdunn** [comment]
Your binary is too old. When I run with `target=pre-assembly`, I get
```
$ cat 0-rawreads/preads/input_preads.fofn
/localdisk/scratch/cdunn/repo/FALCON-examples/run/synth0/0-rawreads/cns-runs/cns_00001/uow-00/consensus.cns_00001.fasta
/localdisk/scratch/cdunn/repo/FALCON-examples/run/synth0/0-rawreads/cns-runs/cns_00002/uow-00/consensus.cns_00002.fasta
```
