### ISSUE TITLE
Falcon install issue

### ISSUE THREAD

**Issue by YuanwenGuo** [PacificBiosciences/FALCON-integrate#193]
Dear developers,

I am trying to install Falcon on slurm system. I followed the commands in "The easy way" to install, but it failed after the "make -j all" step and showed log information below:

make -C ./FALCON-make/ all
make[1]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make show
make[2]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
mkdir -p /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
which python
/opt/software/software/Python/2.7.15-foss-2018b/bin/python
echo "PYTHONUSERBASE=/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env"
PYTHONUSERBASE=/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env
python -c 'import site; print site.USER_BASE'
/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env
echo "FALCON_PIP_EDIT=--edit"
FALCON_PIP_EDIT=--edit
echo "FALCON_PIP_USER=--user"
FALCON_PIP_USER=--user
make[2]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make install-pip
make[2]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
python -c 'import pip; print pip' || python get-pip.py --user
<module 'pip' from '/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/__init__.pyc'>
pip install --user --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (19.1.1)
pip install --user --upgrade setuptools # needed when --edit is used
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: setuptools in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (41.0.1)
pip install --user nose pytest # for running tests while building
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: nose in /opt/software/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg (1.3.7)
Requirement already satisfied: pytest in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (4.5.0)
Requirement already satisfied: funcsigs>=1.0; python_version < "3.0" in /opt/software/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg (from pytest) (1.0.2)
Requirement already satisfied: py>=1.5.0 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (1.8.0)
Requirement already satisfied: pluggy!=0.10,<1.0,>=0.9 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (0.11.0)
Requirement already satisfied: six>=1.10.0 in /opt/software/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/six-1.11.0-py2.7.egg (from pytest) (1.11.0)
Requirement already satisfied: pathlib2>=2.2.0; python_version < "3.6" in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (2.3.3)
Requirement already satisfied: atomicwrites>=1.0 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (1.3.0)
Requirement already satisfied: wcwidth in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (0.1.7)
Requirement already satisfied: more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (5.0.0)
Requirement already satisfied: attrs>=17.4.0 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (19.1.0)
Requirement already satisfied: setuptools in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pytest) (41.0.1)
Requirement already satisfied: scandir; python_version < "3.5" in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest) (1.10.0)
make[2]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make install # This will double -D_GNU_SOURCE, but that is ok for now.
make[2]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB all
make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER all
make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR all
cd /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW; pip uninstall -v .; pip install -v --user --edit .
# TODO: copy vs. symlink?
make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/nim-falcon/src -j1 all
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER'
PREFIX=/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER symlink
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR'
PREFIX=/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR symlink
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/git-sym/git-sym /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin/git-sym
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/nim-falcon/src'
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB'
nim --threads:on --threadAnalysis:off --verbosity:2 -d:release  --tlsemulation:on --out:fc_rr_hctg_track2.exe c fc_rr_hctg_track2.nim
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB'
PREFIX=/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env make -C /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB symlink
make[3]: nim: Command not found
make[3]: *** [fc_rr_hctg_track2.exe] Error 127
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/nim-falcon/src'
make[2]: *** [install-nim-falcon] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER'
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER/datander /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER/TANmask /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER/REPmask /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER/HPC.TANmask /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER/HPC.REPmask /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR'
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR/dexta /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR/undexta /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
make[3]: Entering directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB'
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/fasta2DB /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DB2fasta /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBsplit /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBdust /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/Catrack /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBshow /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBstats /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBrm /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/simulator /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/fasta2DAM /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DAM2fasta /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DBdump /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/rangen /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DEXTRACTOR'
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAMASKER'
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/libdazzdb.a /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib
ln -sf /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/QV.h /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB/DB.h /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/include
make[3]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/DAZZ_DB'
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")
Exception information:
Traceback (most recent call last):
  File "/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pip/_internal/commands/uninstall.py", line 66, in run
    '"pip help %(name)s")' % dict(name=self.name)
InstallationError: You must give at least one requirement to uninstall (see "pip help uninstall")
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Created temporary directory: /tmp/pip-ephem-wheel-cache-_4bQpE
Created temporary directory: /tmp/pip-req-tracker-oUXCOG
Created requirements tracker '/tmp/pip-req-tracker-oUXCOG'
Created temporary directory: /tmp/pip-install-lseXmV
Obtaining file:///bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW
  Added file:///bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW to build tracker '/tmp/pip-req-tracker-oUXCOG'
    Running setup.py (path:/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW/setup.py) egg_info for package from file:///bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW
    Running command python setup.py egg_info
    /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
  Source in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW has version 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef, which satisfies requirement pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef from file:///bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW
  Removed pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef from file:///bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW from build tracker '/tmp/pip-req-tracker-oUXCOG'
Requirement already satisfied: networkx<=1.11,>=1.7 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (1.11)
Requirement already satisfied: future>=0.16.0 in /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages (from pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (0.17.1)
Requirement already satisfied: decorator>=3.4.0 in /opt/software/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/decorator-4.3.0-py2.7.egg (from networkx<=1.11,>=1.7->pypeflow==2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef) (4.3.0)
Installing collected packages: pypeflow
  Found existing installation: pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    Uninstalling pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef:
      Created temporary directory: /tmp/pip-uninstall-BXbaN3
      Removing file or directory /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link
      Removing pth entries from /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/easy-install.pth:
      Removing entry: /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW
      Successfully uninstalled pypeflow-2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
  Running setup.py develop for pypeflow
    Running command /opt/software/software/Python/2.7.15-foss-2018b/bin/python -c 'import setuptools, tokenize;__file__='"'"'/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
    /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef
    ' to '2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef'
      normalized_version,
    running develop
    running egg_info
    writing requirements to pypeflow.egg-info/requires.txt
    writing pypeflow.egg-info/PKG-INFO
    writing top-level names to pypeflow.egg-info/top_level.txt
    writing dependency_links to pypeflow.egg-info/dependency_links.txt
    writing entry points to pypeflow.egg-info/entry_points.txt
    reading manifest file 'pypeflow.egg-info/SOURCES.txt'
    writing manifest file 'pypeflow.egg-info/SOURCES.txt'
    running build_ext
    Creating /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow.egg-link (link to .)
    Adding pypeflow 2.0.1+git.cfb4aceb07ef56f9e1250d6abe123ef9a31762ef to easy-install.pth file
    Installing pwatcher-pypeflow-example script to /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
    Installing heartbeat-wrapper script to /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin
    Installing pwatcher-main script to /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/fc_env/bin

    Installed /bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/pypeFLOW
Successfully installed pypeflow
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-oUXCOG'
make[2]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/bulk/yuanwen/Tools_new/FALCON/FALCON-integrate/FALCON-make'
make: *** [all] Error 2

I am using python module 2.7.15 by "module load Python/2.7.15-foss-2018b"

Could you please help me with this issue? Thank you!

Best,
Yuanwen

**Comment by pb-cdunn** [comment]
Sorry. The code here is way out of date. Please use Bioconda. `conda install pb-assembly`
