### ISSUE TITLE
running falcon and falcon_unzip with HiFi reads

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/FALCON-integrate#194]
To whom it may concern,

I am attempting to run falcon and falcon_unzip through pb-assembly. The fasta header of CCS/HiFi reads does not seem to be compatible with the daligner that is installed together with pb-assembly. I was wondering when PacBio might push an update for pb-assembly that would run with the HiFI reads.

Regards,
Sangjin Lee

**Comment by pb-cdunn** [comment]
We'll take care of that with a special Unzip workflow update, to be released this week.
