### ISSUE TITLE
Installing FALCON-integrate issues 

### ISSUE THREAD

**Issue by ItenIsmail** [PacificBiosciences/FALCON-integrate#195]
Hello ,
We are trying to install Falcon-integrate on our clusters we are following these steps:
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout develop
git submodule update --init --recursive
unset PYTHONPATH
make init
source env.sh
make config-standard
make -j all

and we have nim 0.20.2 installed but we keep getting this error:

Hint: rr_hctg_track [Processing]
Hint: msgpack4nim [Processing]
Hint: streams [Processing]
Hint: endians [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: sequtils [Processing]
Hint: hashes [Processing]
Hint: tables [Processing]
Hint: intsets [Processing]
Hint: lists [Processing]
Hint: deques [Processing]
Hint: typetraits [Processing]
Hint: sets [Processing]
Hint: strtabs [Processing]
Hint: os [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: critbits [Processing]
/sw/csi/falcon-integrate/2018/el7.6_anaconda2/builds/FALCON-integrate/nim-falcon/repos/msgpack4nim/msgpack4nim.nim(470, 6) Error: usage of 'isNil' is a user-defined error
make[3]: *** [fc_rr_hctg_track2.exe] Error 1
make[3]: Leaving directory `/sw/csi/falcon-integrate/2018/el7.6_anaconda2/builds/FALCON-integrate/nim-falcon/src'
make[2]: *** [install-nim-falcon] Error 2
make[2]: Leaving directory `/sw/csi/falcon-integrate/2018/el7.6_anaconda2/builds/FALCON-integrate/FALCON-make'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/sw/csi/falcon-integrate/2018/el7.6_anaconda2/builds/FALCON-integrate/FALCON-make'
make: *** [all] Error 2

Please advise .

Thank you ,
Iten

**Comment by pb-cdunn** [comment]
Falcon-integrate does not have up-to-date source-code, unfortunately. Just use Bioconda.
