### ISSUE TITLE
lack of shebang fails submission on SLURM - Falcon-integrate

### ISSUE THREAD

**Issue by ragowthaman** [PacificBiosciences/FALCON-integrate#21]
Hi,
I am able to use the following config to make falcon run on slurm. However, jobs could not be submitted as shebang ( "#!/bin/sh) is missing in the shell scripts. I am wondering where can I make this adjustment, so it gets included into script files. 

I was attempting to edit ..FALCON-integrate/FALCON/src/py/run_support.py 
and ..FALCON-integrate/FALCON/src/py/mains/run.py. I assume I need to recompile FALCON to make the changes effective.....

Is that okay to do, or am I going crazy there.....

Thanks,
Gowthaman

```
job_type = SLURM
sge_option_da = --mincpus 8 --mem-per-cpu 15000 
sge_option_la = --mincpus 2 --mem-per-cpu 15000 
sge_option_pda = --mincpus 8 --mem-per-cpu 15000 
sge_option_pla = --mincpus 8 --mem-per-cpu 15000 
sge_option_fc = --mincpus 8 --mem-per-cpu 15000 
sge_option_cns = --mincpus 8 --mem-per-cpu 15000 
```

**Comment by ragowthaman** [comment]
It works. I changed _prepend_env_paths() function in run_support.py to add shebang line, compiled. It works. Have not checked for its compatibility in SGE though.

File: FALCON-integrate/FALCON/src/py/run_support.py 

```
def _prepend_env_paths(content, names):
    export_env_vars = ['#!/bin/sh\nexport %(k)s=%(v)s:${%(k)s}' %dict(
        k=name, v=os.environ.get(name, '')) for name in names]
    return '\n'.join(export_env_vars + [content])
```

**Comment by pb-cdunn** [comment]
This has already been fixed by @rlleras on `master`, and I think on `0.4.0`.
- https://github.com/PacificBiosciences/FALCON/pull/181

**Comment by ragowthaman** [comment]
Well, I am using master. I will check this. - Thanks Christopher.

On Sat, Nov 14, 2015 at 10:28 AM, Christopher Dunn <notifications@github.com

> wrote:
> 
> This has already been fixed by @rlleras https://github.com/rlleras on
> master, and I think on 0.4.0.
> - PacificBiosciences/FALCON#181
>   https://github.com/PacificBiosciences/FALCON/pull/181
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PacificBiosciences/FALCON-integrate/issues/21#issuecomment-156730771
> .

## 

Gowthaman Ramasamy PhD.,

Senior Bioinformatics Research Specialist.
_Center for Infectious Disease Research_
307 West lake Ave N Suite 500
Seattle, WA. 98109-5219
Phone : LAB 206-256-7188 (direct).

**Comment by pb-cdunn** [comment]
Ok. Be sure to update submodules. Re-open if it's definitely still a problem in slurm-mode.

**Comment by rlleras** [comment]
Hi Chris,

Let me know if this is confirmed. I have another site using this with no issues, though.

-Roberto

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Sat, Nov 14, 2015 at 10:54 AM -0800, "Christopher Dunn" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok. Be sure to update submodules. Re-open if it's definitely still a problem in slurm-mode.

**Comment by pb-cdunn** [comment]
Slurm, Torque, and LSF all work with the latest code, according to users.
