### ISSUE TITLE
Falcon install error

### ISSUE THREAD

**Issue by yilunhuangyue** [PacificBiosciences/FALCON-integrate#32]
I got an error when installing Falcon,I install the tool by steps:

``` sh
git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout 0.4.0  # or whatever version you want
make init
make virtualenv
make check
make -j install
make test  # to run a simple one
```

but when I type make init,I got the message:

```
git submodule update --init --depth=1 virtualenv
Usage: git submodule [--quiet] add [-b branch] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] update [--init] [-N|--no-fetch] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--] [<path>...]
make: *** [init] 错误 1
```

my machine is Red Hat Enterprise Linux Server release 6.5 (Santiago), and the git version is  1.7.1
python is 2.7.11
I have no idea what is the problem, could anyone give me some advices? thanks a lot.

**Comment by pb-jchin** [comment]
your git version might not too old.

**Comment by yilunhuangyue** [comment]
thanks，I have installed it successfully. but when i run fc_run.py, i got another error:
ConfigParser.NoSectionError: No section: 'General'.
it seems that i lost a section in python .but the python i was using is bundled in Falcon. after typing which python,~/software/falcon/FALCON-integrate/fc_env/bin/python.
so what mistakes i have made?
thanks again

**Comment by pb-cdunn** [comment]
You need to run

```
fc_run.py fc_run.cfg
```

See **FALCON-examples** for examples.

**Comment by yilunhuangyue** [comment]
thanks
