### ISSUE TITLE
symlink: 'run/lambda/data/lambda-creads.fasta' 'data/foo-test' -> '../.git-sym/foo error

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/FALCON-integrate#37]
Trying travis gives:

```
symlink: 'run/lambda/data/lambda-creads.fasta'
'data/foo-test' -> '../.git-sym/foo' does not exist
Traceback (most recent call last):
  File "/net/eichler/vol5/home/mchaisso/software/FALCON-integrate/fc_env/bin/git-sym", line 455, in main
    cmd_table[cmd](**args)
  File "/net/eichler/vol5/home/mchaisso/software/FALCON-integrate/fc_env/bin/git-sym", line 358, in git_sym_update
    git_sym_check(symlinks)
  File "/net/eichler/vol5/home/mchaisso/software/FALCON-integrate/fc_env/bin/git-sym", line 405, in git_sym_check
    raise Exception(symlink)
Exception: data/foo-test
```

**Comment by pb-cdunn** [comment]
What do you mean by "Trying travis"? Any extra info would help.

Note that when you run a repo in TravisCI, they automatically update your git-sub-modules for you. Maybe you need to run `git submodule update --init`. E.g.
- https://travis-ci.org/PacificBiosciences/FALCON-integrate/builds/114886741

**Comment by lcxaiw** [comment]
hello, @mchaisso   I met the same problem. I am confused with it. Have you fixed it? If so, can you tell me how to fix it? Thank you

**Comment by pb-cdunn** [comment]
@lcxaiw, if you still have this problem, please show me the following output:
```sh
# In FALCON-integrate directory
ls -larth
git submodule
git rev-parse HEAD
```

**Comment by lcxaiw** [comment]
@pb-cdunn I have fixed it. Thank you all the same. 
  By the way , I found that the consensus process consumes a lot time. Has anyone tried to make it calculated on GPU? If so, can I see the code? Thanks

**Comment by pb-jchin** [comment]
@lcxaiw do you know if the computation is I/O intensive or CPU intensive?  If it is I/O intensive in your system (depending on your configuration), then GPU will not help.  The current consensus algorithm includes some graph traversal which is probably no straight forward to port to GPU code. I am not GPU coding expert, so I don't really know. The O(ND) alignment algorithm quite efficient, and it maybe possible to be ported to some GPU to further speed it up.

**Comment by pb-cdunn** [comment]
We have a [Nim](https://nim-lang.org/) port of **fc_consensus**. There is an [ArrayFire](https://github.com/arrayfire/arrayfire) wrapper [for Nim](https://github.com/bitstormGER/ArrayFire-Nim), so in theory we could push some operations to a GPU. But I'm experimenting with other optimizations first.

**Comment by lcxaiw** [comment]
@pb-cdunn @pb-jchin Thanks for your help. I will see and try it.
