### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON-integrate#38]
Hi, Chris,

I'm trying to rev up but got this error.

Thanks,
David

error message is:

```
ValueError: A 0.7-series setuptools cannot be installed with
  distribute. Found one at
  /net/gs/vol1/home/dgordon/falcon/160414/FALCON-integrate/fc_env/lib/python2.7\
/site-packages/setuptools-20.7.0-py2.7.egg
```

If I ignore the error, and try to run Falcon, I get this same error.   Anything obvious I did wrong?

**Comment by pb-cdunn** [comment]
Try this:
- https://trac.edgewall.org/wiki/TracFaq#Q:WhydoesinstallingdistributefailwithValueError:A0.7-seriessetuptoolscannotbeinstalledwithdistribute.

Or try some other things. You need consistent versions of setuptools and distribute, independent of Falcon.
