### ISSUE TITLE
problem when install falcon, thanks!

### ISSUE THREAD

**Issue by lamz138138** [PacificBiosciences/FALCON-integrate#44]
Hi, I had install falcon following the guide (https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation). However, it encounter the following error in the step of "make init". I try to replace "git check 0.4.0" to "git check 0.3.0", or simply skip this step, but it didn't work. What should I do? Anything suggestion would be grateful. The error is:

```
fatal: reference is not a tree: 8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49
Unable to checkout '8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49' in submodule path 'virtualenv'
make: *** [init] Error 1
```

**Comment by pb-cdunn** [comment]
This will work now, after an update to the `0.4.0` tag. You will need to update both this repo and the **virtualenv** repo.

The problem is covered in #40.

**Comment by lamz138138** [comment]
Hi, pb-cdunn!
Thank you for your reply very much!
WIth your revision, I had run 'make init' successfully, and I had review #40. However, I had encounter another problem. After google, I think it is hard for me to solve the problem, so I turn to your help. Following is error when running 'make virtualenv':

```
mkdir -p /PATH/FALCON-integrate/fc_env
python2.7 virtualenv/virtualenv.py --no-site-packages  --always-copy /PATH/FALCON-integrate/fc_env
New python executable in /PATH/FALCON-integrate/fc_env/bin/python2.7
Not overwriting existing python script /PATH/FALCON-integrate/fc_env/bin/python (you must use /PATH/FALCON-integrate/fc_env/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /PATH...fc_env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/PATH/FALCON-integrate/virtualenv/virtualenv_support/pip-7.0.3-py2.py3-none-any.whl/pip/__init__.py", line 4, in <module>
  File "/usr/lib64/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref
ImportError: No module named time
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv/virtualenv.py", line 2363, in <module>
    main()
  File "virtualenv/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "virtualenv/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "virtualenv/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "virtualenv/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /rd1/user/zhongxm/Pr...fc_env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
make: *** [virtualenv] Error 1
```

**Comment by pb-cdunn** [comment]
You're on Centos7, right? As mentioned in #39, we don't have a solution for that. But you can try to use **pitchfork** to install everything:
- https://github.com/PacificBiosciences/pitchfork

**Comment by lamz138138** [comment]
Hi，pb-cdunn.

My OS is Gentoo 4.6.3. I failed to solve the problem. In fact, I encounter the "missing module" problem last years when I tried to install cDNA-primer for Iso-seq, but I forget whether I had solve it. 
Also, I try to use pitchfork, but it didn't work with following error. Then, I install falcon-integrate on my ubuntu computer, and it install successfully. It is a pity that I have to solve the problem, since our server is Gentoo. 
Thanks for your suggestion.

```
Following is the error of the pitchfork error:
make -f mk/init.mk init
make[1]: Entering directory `/PATH/pitchfork'
/PATH/pitchfork/bin/checkSystem
/PATH/pitchfork/bin/checkCC gcc
[ERROR] unexpected program error in /PATH/pitchfork/bin/checkCC
make[1]: *** [sanity] Error 1
make[1]: Leaving directory `/PATH/pitchfork'
/PATH/pitchfork/bin/checkSystem
/PATH/pitchfork/bin/checkCC gcc
[ERROR] unexpected program error in /PATH/pitchfork/bin/checkCC
make: *** [sanity] Error 1
```

**Comment by pb-cdunn** [comment]
Would you file that error as an Issue for **pitchfork**? I'm sure you would get a quick response.

**Comment by lamz138138** [comment]
Hi, pb-cdunn!

Sorry for the delay reply. I think the old version of gcc lead to the problem, but I failed to update it. If it still have problem, I would post it on pitchfork.

Thanks for your help!

**Comment by lamz138138** [comment]
Hi, it's me again.

I had solve the problem in the step of 'make virtualenv' by changing " 'lib' " to "lib_dir" as suggested in #39. Everything look well until 'make -j install', which output following error. Gcc in my OS is 4.6.3, I had tried to use 4.8.2, but it didn't work.

The error in 'make -j install':

```
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/c/ext_falcon.c -o build/temp.linux-x86_64-2.7/src/c/ext_falcon.o
In file included from /usr/include/limits.h:25:0,
                 -----from /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/include-fixed/limits.h:169,
                 -----from /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/include-fixed/syslimits.h:7,
                 -----from /usr/lib/gcc/x86_64-pc-linux-gnu/4.6.3/include-fixed/limits.h:34,
                 -----from /usr/include/python2.7/Python.h:19,
                 -----from src/c/ext_falcon.c:1:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/c/DW_banded.c -o build/temp.linux-x86_64-2.7/src/c/DW_banded.o
In file included from /usr/include/stdlib.h:24:0,
                 -----from src/c/DW_banded.c:59:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/c/kmer_lookup.c -o build/temp.linux-x86_64-2.7/src/c/kmer_lookup.o
In file included from /usr/include/stdlib.h:24:0,
                ----- from src/c/kmer_lookup.c:56:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c src/c/falcon.c -o build/temp.linux-x86_64-2.7/src/c/falcon.o
In file included from /usr/include/stdlib.h:24:0,
                ----- from src/c/falcon.c:56:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
src/c/falcon.c: In function 'get_cns_from_align_tags':
src/c/falcon.c:474:5: error: 'g_best_score' undeclared (first use in this function)
src/c/falcon.c:474:5: note: each undeclared identifier is reported only once for each function it appears in
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
make[1]: *** [build-FALCON] Error 1
make[1]: Leaving directory `/myPath/FALCON-integrate/FALCON-make'
make: *** [install] Error 2
```

**Comment by pb-cdunn** [comment]
No idea. But first update to **FALCON-integrate 0.5.0**.

**Comment by lamz138138** [comment]
Thanks!

I would try FALCON-integrate 0.5.0.

**Comment by lamz138138** [comment]
Hi, pb-cdunn!

I may have solve the  problem, but I don't know whether I am right. I think there is a bug in the file of "FALCON/src/c/falcon.c", the position of "assert(g_best_score != -1); " may be wrong. I had tried to comment this line "//assert(g_best_score != -1);", or move this line before line 473 (that is, before the "}"), then I could install successfully. But I don't know why it didn't  output error in ubuntu, do you think I am right to move the line of "assert(g_best_score != -1); ", or how should I check whether falcon is setup correctly?

**Comment by pb-cdunn** [comment]
Yes, I see what you mean. Just move that assertion up one line.
- https://github.com/PacificBiosciences/FALCON/blob/master/src/c/falcon.c#L476

I will update our code with your fix.

**Comment by lamz138138** [comment]
OK, thanks!
