### ISSUE TITLE
sg_edges_list padding with spaces breaks Falcon2Fastg

### ISSUE THREAD

**Issue by dbtara** [PacificBiosciences/FALCON-integrate#45]
The new version of output of sg_edges_list with space padding makes it easier to read the file but breaks Falcon2Fastg.py, as it is expecting only a single space as delimiter.

`read_pairs_TMI = csv.reader(sg_entries, delimiter=' ')`

Just wanted to let you know

**Comment by pb-cdunn** [comment]
Thanks! I've alerted the owners of **md5sam**.

**Comment by md5sam** [comment]
@dbtara Thank you for flagging this - it is now fixed in Falcon2Fastg v0.3.1
