### ISSUE TITLE
Special dot to the end of line

### ISSUE THREAD

**Issue by michaelf63** [PacificBiosciences/FALCON-integrate#5]
Hi,
I have a problem:
Starting fc_run.py conf_file, the created prepare_db.sh contains a dot to the end of line ...done >> db_build.log

![red_dot](https://cloud.githubusercontent.com/assets/13556166/8958971/6687fa9c-3608-11e5-8580-060f29b90cd7.png)

Without this caracter, the pipeline works...

**Comment by pb-cdunn** [comment]
That line has been commented out:
- https://github.com/PacificBiosciences/FALCON/blob/master/src/py/mains/run.py#L146

What commit of FALCON are you using?

```
cd FALCON; rev-parse HEAD
```

**Comment by michaelf63** [comment]
I use :
[1:1959]$ git rev-parse HEAD
cee6a580e97b209ff4d025b402a9f2c180c30bff
But I think, I use the  wrong starting process may be?
../FALCON/build/scripts-2.7/fc_run.py fc_run.cftg

**Comment by michaelf63** [comment]
I found, another old version of FALCON works in the same time...
Thanks.
