### ISSUE TITLE
Questions - on setting up fc_run.cfg for a 250-350 Mb insect genome with 30-50X coverage

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/FALCON-integrate#54]
Hi,

Thanks for helping me get up and running with Falcon in #50 and #53 !!!

I am about to embark on some parameter optimization and since everything takes a long time, I am hoping you can advise the best starting conditions -- specific questions below. Also, can you let me know how to restart from where falcon left off if it is killed by SLURM for either going over an allotted amount of time or memory (or for any other reason)? 

Do you have any recommendations for 30-50X data for a 250-350 Mb insect genome? In particular, do you have a fc_run.cfg file or can you help me set one up that would be best to start with for that?

Even more specific:
- do I set genome_size or leave it commented out?
- should I set length_cutoff and length_cutoff_pr to -1 -- for auto-selecting those?
- where it says `jobqueue = production`, what does that do and is there documentation explaining other options?
- do you have recommendations for time lengths, amount of memory, and number of CPUs for:
  sge_option_da = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 10g --time 00:20:00 
  sge_option_la = --ntasks 1 --nodes 1 --cpus-per-task 2 --mem 10g --time 00:05:00 
  sge_option_pda = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 15g --time 00:20:00 
  sge_option_pla = --ntasks 1 --nodes 1 --cpus-per-task 2 --mem 10g --time 00:05:00 
  sge_option_fc = --ntasks 1 --nodes 1 --cpus-per-task 16 --mem 10g --time 00:20:00 
  sge_option_cns = --ntasks 1 --nodes 1 --cpus-per-task 8 --mem 10g --time 00:20:00
- for the following, does the number put there limit how many jobs can be submitted to slurm at a given time? I ask b/c I can submit any number of jobs, they will just sit in the pending/queue until there are resources for them.
  pa_concurrent_jobs = 32
  cns_concurrent_jobs = 32
  ovlp_concurrent_jobs = 32
- what are recommended paramters for the following functions for the genome size and amount of coverage given above:
  pa_DBsplit_option =   -a -x5 -s.065536
  ovlp_DBsplit_option = -a -x5 -s50
  falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 1 --max_n_read 20000 --n_core 0
  overlap_filtering_setting = --max_diff 10000 --max_cov 100000 --min_cov 1 --min_len 1 --bestn 1000 --n_core 0

Many thanks for any tips you can give me here.

**Comment by pb-cdunn** [comment]
> Do you have any recommendations for 30-50X data for a 250-350 Mb insect genome?
> do I set genome_size or leave it commented out?
> should I set length_cutoff and length_cutoff_pr to -1 -- for auto-selecting those?

These are related. I suggest:

``` ini
length_cutoff = -1
genome_size = 350000000
seed_coverage = 30
```

> where it says jobqueue = production, what does that do and is there documentation explaining other options?

That's for SGE users, so they can fill in the `%queue` for all sge settings. You might not need that for Slurm.

> do you have recommendations for time lengths, amount of memory, and number of CPUs?

I don't know what `--ntasks` and `--nodes` are for, and it's hard to estimate run-times in advance. (Someday, but not yet.) CPUs are easy. Memory depends on your `-M` setting and your block sizes, but what you have is a good start:

``` ini
sge_option_da = --cpus-per-task 8 --mem 10g
sge_option_la = --cpus-per-task 2 --mem 10g
sge_option_pda = --cpus-per-task 8 --mem 10g
sge_option_pla = --cpus-per-task 2 --mem 10g
sge_option_fc = --cpus-per-task 16 --mem 10g
sge_option_cns = --cpus-per-task 8 --mem 10g
```

> for the following, does the number put there limit how many jobs can be submitted to slurm at a given time? I ask b/c I can submit any number of jobs, they will just sit in the pending/queue until there are resources for them.
> pa_concurrent_jobs = 32
> cns_concurrent_jobs = 32
> ovlp_concurrent_jobs = 32

Yes, these would limit simultaneous submissions. For you, these can be huge. But when you run with `job_type=local`, then these should be low.

> what are recommended paramters for the following functions for the genome size and amount of coverage given above?

@pb-jchin is the expert on those settings. But you could try with those.

**Comment by JohnUrban** [comment]
Thanks for the answer.

I actually do not need/want to set `--nodes` and `--ntasks`. I found a SLURM fc_run.cdg online  that I hastily copy/pasted when trying to get it to run. Now that you point them out, I will just remove them and use `--cpus-per-task`, `--time`, and `--mem`.

By the way, if you don't have one already, including an example SLURM fc_run.cfg somewhere in FALCON-examples would be extremely helpful for slurm people -- I had to scrape the internet.  When I first embarked on all this, it seemed overwhelming - though now it seems manageable and more clear after working with it for a few days.

**Comment by pb-cdunn** [comment]
You, sir, are going to be the source of our SLURM example. When you get it working, if you post settings and the actual command-line, we should be able to get `fc_run1` working and add docs.

**Comment by pb-cdunn** [comment]
Feel free to re-open if have further questions.

**Comment by JohnUrban** [comment]
Hi again @pb-cdunn ,

I actually just ran Falcon on real data for the first time -- the run started yesterday. Recall - I am on SLURM, in case that will matter. I should also say I am running the version of 0.6.2 that I modified (with your help) to get it working for SLURM (https://github.com/PacificBiosciences/FALCON-integrate/issues/53). I see you have made a lot of changes since - I will try installing the latest stuff, but I kind of also wanted to go with what I know already works (on Synth0, Lambda, and Ecoli) to start out.

A few questions:
1.) I had to restart a few times because it kept getting killed for exceeding memory around the fc_fasta2fasta step and/or the fasta2DB step. It started out as:
`sge_option_da = --cpus-per-task 8 --mem 10g --time 24:000:00`

I then tried 30g:
`sge_option_da = --cpus-per-task 8 --mem 30g --time 24:000:00`

Ultimately 60g "worked":
`sge_option_da = --cpus-per-task 8 --mem 60g --time 24:000:00`

2.) I have my reads from multiple SMRT cells in the same file, so it seems like the stderr says fc_fasta2fasta put them into separate files, for example:

./0-rawreads/19b56bb3909991b7425907cebf7dc48e/m131208_010315_42177R_c10059103255000000183103405221497_s1_p0.fasta

Is that correct?
What seems weird is that I never actually saw those files in the 0-rawreads/ directory and I was checking fairly frequently to see what was happening.

3.) The fasta2DB parts in 0-rawreads/pwatcher.dir/stderr seemed to suggest the reads were being loaded into a database called "raw_reads". However, I cannot find it anywhere.

4.) Falcon has been hanging on this step for ~10 hours (this is right after all the fasta2DB and DBsplit):

```
$ tail 0-rawreads/pwatcher.dir/stderr 

rm -f run_jobs.sh
+ rm -f run_jobs.sh
CUTOFF=$(python -m falcon_kit.mains.calc_cutoff --coverage 30.0 292000000 <(DBstats -b1 raw_reads))
++ python -m falcon_kit.mains.calc_cutoff --coverage 30.0 292000000 /dev/fd/63
+++ DBstats -b1 raw_reads
+ CUTOFF=7230
echo -n $CUTOFF >| length_cutoff
+ echo -n 7230
HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000  -H$CUTOFF raw_reads 1-$LB >| run_jobs.sh
+ HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000 -H7230 raw_reads 1-182664
```

Is that normal?

5.) Given the trouble I had with memory issues for this very early step, any memory recommendations for these (?):

```
sge_option_da = --cpus-per-task 8 --mem 60g --time 24:000:00 
sge_option_la = --cpus-per-task 2 --mem ___ --time 24:00:00 
sge_option_pda = --cpus-per-task 8 --mem ___ --time 24:00:00 
sge_option_pla = --cpus-per-task 2 --mem ___ --time 24:00:00 
sge_option_fc = --cpus-per-task 16 --mem ___ --time 24:00:00 
sge_option_cns = --cpus-per-task 8 --mem ___ --time 24:00:00 
```

6.) Finally, fc.log is getting pretty big quite early in the game. Does my `logging.ini` file have anythign to do with that. It looks like this (lots of DEBUG level stuff):

```
[loggers]
keys=root,pypeflow,fc_run

[handlers]
keys=stream,file_pypeflow,file_fc_run,file_all

[formatters]
keys=form01,form02

[logger_root]
level=NOTSET
handlers=stream,file_all

[logger_pypeflow]
level=NOTSET
handlers=file_pypeflow
qualname=pypeflow
propagate=1

[logger_pwatcher]
level=NOTSET
handlers=file_pwatcher
qualname=pwatcher
propagate=1

[logger_fc_run]
level=NOTSET
handlers=file_fc_run
qualname=fc_run
propagate=1

[handler_stream]
class=StreamHandler
level=INFO
formatter=form02
args=(sys.stderr,)

[handler_file_pypeflow]
class=FileHandler
level=DEBUG
formatter=form01
args=('pypeflow.log',)

[handler_file_pwatcher]
class=FileHandler
level=DEBUG
formatter=form01
args=('pwatcher.log',)

[handler_file_fc_run]
class=FileHandler
level=DEBUG
formatter=form01
args=('fc_run.log',)

[handler_file_all]
class=FileHandler
level=DEBUG
formatter=form01
args=('fc.log',)

[formatter_form01]
format=%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s

[formatter_form02]
format=[%(levelname)s] %(message)s
```

What are the options for level?

Thanks for all of your help.

**Comment by JohnUrban** [comment]
Additional questions:
7) Is there a page that describes all the options in fc_run.cfg and the logic for choosing parameters based on genome size, coverage, system, etc?

8) In my fc_run.cfg, which I scrambled together from bits and pieces of cfg files I found here and there, I have a line that says:

```
use_tmpdir = true
```

Should I get rid of that?

**Comment by pb-cdunn** [comment]
1. Yes, knowing the resource requirements can be tricky.
2. fc_fasta2fasta: When you update to 0.7.3, you won't need fasta2fasta anymore.
3. `0-rawreads/raw_reads.db`
4. "Is 10 hours normal for build_rdb?" No! That step is very fast. Try to quit, `rm -rf mypwatcher/`, and restart. Otherwise, you have to find the job in Slurm and investigate. Maybe it never starts?
5. What you have should be fine, I think.
6. Change all `DEBUG` into `INFO`. However, that will reduce my ability to help you. As for the options, google "Python logging config".
7. Options? See wiki. That's all we have for now.
8. `use_tmpdir = true`. Drop only if you run out of disk-space in `/tmp`. It can reduce the load on your network.

**Comment by JohnUrban** [comment]
Thanks.
As for (3): `0-rawreads/raw_reads.db` is not there... though it is past that part.

I will try quitting/restarting as you suggested.
Thanks again.

**Comment by JohnUrban** [comment]
Is it correct to assume there are some HUGE memory spikes in the HPC.daligner step?
`HPC.daligner -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000 -H22131 raw_reads 1-13936`

I ask because I am currently trying to get past this step with ecoli data, and it keeps failing due to exceeding memory. However, when I check the max amount of memory used, its way below the amount allotted. Since slurm just samples memory usage, I guess there could be short spikes of high memory requirement that is killing the job.... I don't know -- other than that, I really cannot see why it keeps failing due to memory issues.

Also, which option gives memory to this -- I assume:
`sge_option_da = --cpus-per-task 8 --mem 60g --time 24:000:00`

**Comment by pb-cdunn** [comment]
Yes, the `HPC.daligner` call is currently submitted according to the `sge_option_da` parameters.

Spikes? `HPC.daligner` should be cheap, but it runs as part of a larger script. Look at `0-rawreads/prepare.*.sh`. `fasta2DB` could have a memory spike.

**Comment by JohnUrban** [comment]
What would you say is the normal size range for `0-rawreads/run_jobs.sh` for an ecoli run with ~70X data?

I tried using the cfg file I was using on the insect with Ecoli -- right now it is at 22 GB --- full of daligner commands.

Also, as far as use_tmpdir goes, the sys admins got in touch with me to let me know that was causing issues on my system and may also explain (partially) why I couldn't get the insect run to go. It was trying to use more space than available (30 GB) -- which seems related to this large run_jobs.sh file thing I mentioned above.

Also, part of why I couldn't see raw_reads.db nor this large run_jobs.sh earlier is that there is a different /tmp on each node -- and I guess I can only see the /tmp on the login node.

**Comment by JohnUrban** [comment]
Final size of that `0-rawreads/run_jobs.sh` for the 70X ecoli run is 25 GB and has 71,340,993 lines.

**Comment by JohnUrban** [comment]
I can see that `0-rawreads/run_jobs.sh` is only 51 KB (with 199 lines) when using the fc_run.cfg example from FALCON-examples.
Any thoughts on what lines in the config file matter here...?

I'm currently comparing it to the cfg provided for the ecoli example, and also making minor changes incrementally to see the effect. I will let you know what I find.

**Comment by pb-cdunn** [comment]
> Also, part of why I couldn't see raw_reads.db nor this large run_jobs.sh earlier is that there is a different /tmp on each node -- and I guess I can only see the /tmp on the login node. 

That doesn't make any sense. Something is odd.

> Final size of that 0-rawreads/run_jobs.sh for the 70X ecoli run is 25 GB and has 71,340,993 lines.

Haha! You should probably use `*concurrency=1` and `job_type=local` until you know you have good job-size. Could you post your config? I noticed `-h1 -w1`, which could be your main problem. You can easily run `HPC.daligner` from the command-line. Start with the **FALCON-examples** and gradually adjust that to see what the jobs will look like.

**Comment by JohnUrban** [comment]
Yeah - I have been digging around at the Dazzler blog and the wiki/manual to get a better grasp of all the options. The ecoli runs were successful with the provided fc_run.cfg. I realized the runs that were un-successful were the ones using much of the synth0 fc_run.cfg file.

Synth0

```
pa_HPCdaligner_option =   -v -B4 -t50 -h1 -e.99 -w1 -l1 -s1000
ovlp_HPCdaligner_option = -v -B4 -t50 -h1 -e.99 -l1 -s1000
pa_DBsplit_option =   -a -x5 -s.065536
ovlp_DBsplit_option = -a -x5 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 1 --max_n_read 20000 --n_core 0
overlap_filtering_setting = --max_diff 10000 --max_cov 100000 --min_cov 1 --min_len 1 --bestn 1000 --n_core 0
```

Ecoli

```
pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24
```

The runs on the insect genome (~300 Mb) were essentially using the ecoli fc_run.cfg file. These runs seem to have the same problem the ecoli runs have when run with the synth0 cfg, so it looks like I need to make further adjustments for the bigger genome/data set. Perhaps it should be more closely modeled after the arab cfg. I am still processing what -B is and how a number is chosen -- as well as -h in ovlp_HPCdaligner_option (and why -h is not in pa_).

Arabidopsis:

```
pa_HPCdaligner_option =  -v -B128 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B128 -t32 -h60 -e.96 -l500 -s1000
pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -x500 -s400
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 1 --bestn 10 --n_core 24
```

I could also try modeling after something I saw Jason Chin recommend as starting parameters for a 400 Mb genome in the issues somewhere -- though it is the first time I saw `falcon_sense_skip_contained = False` or that option at all so far:

```
pa_HPCdaligner_option =  -v -dal128  -e0.75 -M24 -l2500 -k18 -h1250 -w8 -s100
ovlp_HPCdaligner_option =  -v -dal128  -M24 -k24 -h1250 -e.96 -l1500 -s100
pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200
falcon_sense_option = --output_multi --output_dformat --min_idt 0.70 --min_cov 4 --max_n_read 400 --n_core 8
falcon_sense_skip_contained = False
overlap_filtering_setting = --max_diff 120 --max_cov 120 --min_cov 4 --n_core 12
```

**Comment by pb-cdunn** [comment]
> I realized the runs that were un-successful were the ones using much of the synth0 fc_run.cfg file.

That contrived example has perfectly sampled reads. It's only for integration testing (being extremely fast).

> The runs on the insect genome (~300 Mb) were essentially using the ecoli fc_run.cfg file. These runs seem to have the same problem the ecoli runs have when run with the synth0 cfg

Maybe start with the Human example and work backwards?

> (and why -h is not in pa_)

It defaults to `-h35`, but personally I prefer to provide it explicitly.

**Comment by JohnUrban** [comment]
There does not seem to be a human example that comes with the code. Any chance you can point me in the right direction. For the time being I also am comparing what you guys did in the falcon preprint for the arabidopsis and the various grapes.

**Comment by pb-cdunn** [comment]
True. But you can search the _FALCON_ Issue archives in GitHub. Or this might help:

```
genome_size = 3000000000
seed_coverage = 30
cns_concurrent_jobs = 32
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
length_cutoff = -1
length_cutoff_pr = 500
overlap_filtering_setting = --max_diff 40 --max_cov 80 --min_cov 2 --n_core 12
ovlp_DBsplit_option = -x15000 -s40
ovlp_HPCdaligner_option =  -v -B4 -k24 -e.96  -s200 -M16 -l2500 -h1024
ovlp_concurrent_jobs = 32
pa_DBsplit_option = -a -x500 -s500
pa_HPCdaligner_option =    -v -B4 -k18 -e0.70 -s200 -M16 -l4800 -h480 -w8
```

**Comment by JohnUrban** [comment]
Thank you. I have been searching the issues as well, but did not see human. Nonetheless, this should be helpful. At the moment I have something similar to:
V. vinifera Assembly in falcon paper (500 Mb genome) -- 140X cov

```
length_cutoff = 5000
length_cutoff_pr = 5000
pa_HPCdaligner_option = -v -dal128 -e0.75 -M24 -l2500 -k18 -h1250 -w8 -s100
ovlp_HPCdaligner_option = -v -dal128 -M24 -k24 -h1250 -e.96 -l1500 -s100
pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200
falcon_sense_option = --output_multi --output_dformat --min_idt 0.70 --min_cov 4 --max_n_read 400 --n_core 8
falcon_sense_skip_contained = False
overlap_filtering_setting = --max_diff 120 --max_cov 120 --min_cov 4 --n_core 12
```

With a few changes:

```
pa_HPCdaligner_option = -v -B128 -e0.70 -M24 -l1000 -k18 -h1250 -w8 -s100
ovlp_HPCdaligner_option = -v -B128 -M24 -k24 -h1250 -e.96 -l500 -s100
pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
falcon_sense_skip_contained = False
overlap_filtering_setting = --max_diff 120 --max_cov 120 --min_cov 4 --n_core 12
```
