### ISSUE TITLE
No HEARTBEAT, race-condition?

### ISSUE THREAD

**Issue by yfu** [PacificBiosciences/FALCON-integrate#56]
I tried running FALCON-integrate on our LSF system. The synth0 example works. However, if I try a real dataset (which is much larger than synth0), it will throw this error:

```
[ERROR] Task Fred{'URL': 'task://localhost/d_0005_raw_reads'}
 is DEAD, meaning no HEARTBEAT, but this can be a race-condition. If it was not killed, then restarting might suffice. Otherwise, you might have excessive clock-skew.
[INFO] Failure ('fail'). Joining 'task://localhost/d_0005_raw_reads'...
[INFO] tick: 128, #updatedTasks: 6, sleep_time=1.000000
[WARNING]   File "/home/yf60w/FALCON-integrate/fc_env/bin/fc_run", line 9, in <module>
    load_entry_point('falcon-kit', 'console_scripts', 'fc_run')()
  File "/home/yf60w/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 542, in main
    main1(argv[0], args.config, args.logger)
  File "/home/yf60w/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 387, in main1
    wf.refreshTargets(exitOnFailure=exitOnFailure)
  File "/home/yf60w/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
    rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/yf60w/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
    numAliveThreads = self.thread_handler.alive(task2thread.values())
  File "/home/yf60w/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 197, in alive
    fred.endrun(status)
  File "/home/yf60w/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 73, in endrun
    log.warning(''.join(traceback.format_stack()))

```

Even though it throws this error, jobs are actually still running on the cluster, which is quite bizarre... 

```
ghpcc06:pwatcher.dir yf60w$ bjobs
JOBID      USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
3245493    yf60w   RUN   long       ghpcc06     4*c06b01    *764a06961 Jun  3 18:22
3245494    yf60w   RUN   long       ghpcc06     4*c07b07    *bb5207e04 Jun  3 18:22
```

What is causing all these?

**Comment by pb-cdunn** [comment]
Lots of possible causes. When nothing is running anymore, you can simply restart and it might pass.

Until then, look into the `mypwatcher` directory. Somehow, you should be able to figure how which job corresponds to `d_0005_raw_reads`. The stderr/stdout logs might be informative, or maybe you can query LSF after you learn the batch job name. Please let us know whatever you learn.

**Comment by yfu** [comment]
So I tried it again and this time I got the same error with `d_0000_raw_reads`. I checked stderr/stdout in `mypwatcher` and this is what I found:

In `stdout`

```
TERM_OWNER: job killed by owner.
Exited with signal termination: Alarm clock.

Resource usage summary:

    CPU time :                                   152.37 sec.
    Max Memory :                                 56875 MB
    Average Memory :                             22576.67 MB
    Total Requested Memory :                     256000.00 MB
    Delta Memory :                               199125.00 MB
    Max Processes :                              8
    Max Threads :                                14
    Run time :                                   36 sec.
    Turnaround time :                            53 sec.

The output (if any) is above this job summary.

```

In the last few lines of `stderr`,

```
daligner -v -H1000 -e0.7 -M64 raw_reads.1 raw_reads.1
+ daligner -v -H1000 -e0.7 -M64 raw_reads.1 raw_reads.1
touch /project/umw_zhiping_weng/fuy2/cl/results/2016-06-03-smrt-all/0-rawreads/job_0000/job_0000_done.exit
++ touch /project/umw_zhiping_weng/fuy2/cl/results/2016-06-03-smrt-all/0-rawreads/job_0000/job_0000_done.exit
 returned: 2
```

It seems that the owner of the job killed it? And `touch`ing a file returned status 2?

**Comment by pb-cdunn** [comment]
I guess `touch` failed because the directory had not been created yet.

I think the `job killed by owner` message is from you hit `Ctrl-C`. I guess. Not sure.

But the `DEAD` part we cannot yet diagnose. You can follow the instructions here:
- https://github.com/PacificBiosciences/pypeFLOW/issues/22

(I need to put the debug logging-config into a more obvious location.)

**Comment by yfu** [comment]
I just reran it. I had the same errors with the previous run: `touch` returned 2 and `job killed by owner`. I think when the FALCON detects one job fails, it will try to kill other jobs and that may be why I saw `job killed by owner`.

I then tried to increase `ALLOWED_SKEW_S` (from issue 22) to 100 and now it works! What should I ask my sysadmin to solve this problem? Should I just ask them if there a clock-skew between the compute node and the head node?

Thanks a lot!

**Comment by pb-cdunn** [comment]
See other reply.

**Comment by pb-cdunn** [comment]
>  I think when the FALCON detects one job fails, it will try to kill other jobs.

Yes, that's what it does by default. We need to see the logging for the _first_ job to die to so we can diagnose this.

I have pushed out a change to default logging in **FALCON**. In a new directory, could you run the synth0 example (or this one) and see if you can get a log message? I REALLY REALLY want to see some logging from the first job to fail.

>  What should I ask my sysadmin to solve this problem? Should I just ask them if there a clock-skew between the compute node and the head node?

Just discuss it. The sysadmin will know. Clock-skew is probably not an issue, but it was at Amazon, so you never know. More likely, your filesystem has long delays before a file created on one machine is visible to another machine. So it's probably not an issue of "skew", though that's what the variable is called.

**Comment by pb-cdunn** [comment]
Increased the default tolerance for latency in the filesystem. And if it recurs, hopefully the DEBUG logging will show us why.
