### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by liuqianhn** [PacificBiosciences/FALCON-integrate#58]
Hi Dr. Chin,

I am learning how to use FALCON-integrate for genome assembly. When I run FALCON on chm1, I keep getting a memory issue. I tried to change the values of -B and -s, but I still obtained the memory issue. The detail of the issue and the cfg configuration file are given below. 

**Could you please let me know which parameters could be used to control consumed memory less than 20 GB** (As shown below, it was 42.97Gb if my understanding of the error message is correct.)?  Thank you very much. Have a nice weekend!

```
fc_run - WARNING - '/home/qianliu/tutorial/falcon_test/chm1_test2/0-rawreads/job_a9f0fde6/job_a9f0fde6_done' is missing.
job: 'rj_a9f0fde6.sh-d_a9f0fde6_raw_reads-d_a9f0fde6_raw_reads' failed!*
```

I then examined the `rj_a9f0fde6.sh-d_a9f0fde6_raw_reads-d_a9f0fde6_raw_reads.o` file under `sge_log`, and found the memory issue below.

>  Comparing raw_reads.58 to raw_reads.1
> 
>    Capping mutual k-mer matches over 10000 (effectively -t100)
>    Hit count = 1,088,830,730
>    Highwater of 42.97Gb space
> daligner: Out of memory (Reallocating dazzler sort vectors)
> daligner: Out of memory (Allocating dazzler hit vectors)

My cfg configure file is:

```
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 10000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 6000


sge_option_da = -pe smp 4 -l h_vmem=7.5g
sge_option_la = -pe smp 6
sge_option_pda = -pe smp 4 -l h_vmem=7g
sge_option_pla = -pe smp 6
sge_option_fc = -pe smp 12
sge_option_cns = -pe smp 6

pa_concurrent_jobs = 32
cns_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -B4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -B4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 12

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2 --n_core 12
```

Best regards,
Qian

**Comment by pb-cdunn** [comment]
> pa_HPCdaligner_option =  -v -B4 _-t16_ -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -B4 _-t32_ -h60 -e.96 -l500 -s1000

Try this:

> pa_HPCdaligner_option =  -v -B4 -M7 -e.70 -l1000 -s1000
> ovlp_HPCdaligner_option = -v -B4 -M7 -h60 -e.96 -l500 -s1000

I think you'll end up with many more _jobs_, but they should each fit within your `7GB` SGE node allotment.

**Comment by pb-cdunn** [comment]
Actually, with `-s50` for **DBsplit**, you can probably use `-M4`, and `h_mem=4g`.

**Comment by liuqianhn** [comment]
Hi Dr. Chin,

Thank you very much for your reply and your suggestions. I am running FALCON according to your suggestion. 

In my SGE node, each job is allowed to have 30G memory, because four cores will be used each with 7.5g memory (“sge_option_da = -pe smp 4 -l h_vmem=7.5g”). Thus, I changed -M7 to -M30. Please correct me if I am wrong. Thank you very much for your help!

Best regards,
Qian

**Comment by liuqianhn** [comment]
Hi Dr. Chin,

I obtained the memory error again. May I know what is wrong with my cfg file or how to control the memory usage for each job? Thank you very much!

The error message is:

> Comparing raw_reads.138 to raw_reads.83
>    Capping mutual k-mer matches over 10000 (effectively -t100)
>    Hit count = 790,498,485
>    Highwater of 29.51Gb space
> daligner: Out of memory (Allocating dazzler hit vectors)

The cfg file is:

```
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000


sge_option_da = -pe smp 4 -l h_vmem=8g
sge_option_la = -pe smp 6
sge_option_pda = -pe smp 4 -l h_vmem=7g
sge_option_pla = -pe smp 6
sge_option_fc = -pe smp 12
sge_option_cns = -pe smp 6

pa_concurrent_jobs = 60
cns_concurrent_jobs = 40
ovlp_concurrent_jobs = 40

pa_HPCdaligner_option =  -v **-dal32 -M32** -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v **-dal32 -M32** -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 12

overlap_filtering_setting = --max_diff 60 --max_cov 60 --min_cov 2 --n_core 12
```

best regards,
Qian Liu

**Comment by pb-cdunn** [comment]
I think the problem is that you have more than one job on a machine. The job uses less than 30GB, but it runs out of memory anyway. You need to look for the qsub line, then run the underlying script yourself on a dedicated machine and see if it still fails. Also, watch the process (maybe using `top`) while it runs to see actual memory use.

**Comment by pb-cdunn** [comment]
You may re-open if you encounter more problems. But if so, please supply us as much information about your system as possible.
