### ISSUE TITLE
FALCON-integrate release funzip_052016 comes with wrong pypeFLOW commit

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON-integrate#65]
FALCON-integrate release funzip_052016 (ffbc609057741896dbe9d09f65bc5c8ef8d57f5a) contains wrong pypeFLOW commit. It should be e880e2b3cebe7ae19f3101a497a0a8cc6685588e according to the paper and @pb-jchin.

**Comment by pb-cdunn** [comment]
Corrected. Thanks.
