### ISSUE TITLE
FALCON doesn't work with other (non-PacBio) read formats

### ISSUE THREAD

**Issue by gringer** [PacificBiosciences/FALCON-integrate#67]
It would be nice to be able to try this assembler out on my own data (nanopore reads), but the code expects a very specific FASTA file header:

``` sh
$ while read fn; do fasta2DB -v raw_reads $fn; done < /bioinf/data/reads_Jodie_gDNA_2016_Jun_20/downloads/Nb_mt_FALCON/0-rawreads/input.fofn
Adding 'Mitoch_all_Jodie_gDNA_2016_Jun_20.fasta' ...
File Mitoch_all_Jodie_gDNA_2016_Jun_20.fasta, Line 1: Pacbio header line format error
```

**Comment by pb-cdunn** [comment]
Look for `fasta2fasta.py`, or `fc_fasta2fasta`. I think you can use that to translate your headers. That used to be in the default workflow, but it was taking too much time for large genomes.

However, we cannot offer support on non-PB workflows. If it works for you, great!

**Comment by pb-jchin** [comment]
@gringer, in fact, there will be different characteristic of the data. I won't recommend you use this for other types of data for simple reason. We don't test it for other type data. You will probably best contact the vendor to support you. You are a customer of theirs and they should help.
