### ISSUE TITLE
changing default logging level for large runs

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON-integrate#69]
Hello,

I see in the 0.6.2 release notes the following comment. (I assume this is still the case in latest version 0.7.2):
Default logging at DEBUG. Helps me debug user queries, but users will need to turn that down for large runs.

We run large data sets.  What would I observe with the default debug level, and what level should I set it to if I don't want debug logging as well as where to set it?  I couldn't find details snooping around the wiki or falcon-examples.  Possibly the logging.ini file but not sure if this can be manually created and how to set that up.

Thanks!

**Comment by pb-cdunn** [comment]
Yes, you can copy and modify `logging.ini`, and you can pass that filename to `fc_run` as the `--logging` option. For details on the logging configuration, google "python logging config".

Always run on "FALCON-examples/run/synth0" with new logging-config before trying a large genome, so you can see what you will get.

> (I assume this is still the case in latest version 0.7.2)

Yes. It facilitates debugging via GitHub.
