### ISSUE TITLE
Error with falcon-kit

### ISSUE THREAD

**Issue by ademcan** [PacificBiosciences/FALCON-integrate#74]
Dear FALCON devs,
Thank you for this nice tool. I managed to install FALCON and launch it but it always end up with the same error, such as follow:

``` py
Traceback (most recent call last):
  File "${MYHOME}/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').require('falcon-kit==0.7+git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2927, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 635, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a' distribution was not found and is required by the application
```

The identifiers following the 0.7+git seems a bit awkward to me and I was wondering if this is normal (I am using the master branch).
Thank you very much for your help.
A.

**Comment by pb-cdunn** [comment]
Anything in the version string after `+` is ignored by `pkg_resources`, so we use that to store the Git SHA1, for tracking. That part is not a problem. It is possible that your `setuptools` Python package is too old, or maybe your Python itself. Or you are missing an env-var. Or you simply did not install properly.

Did you follow all the instructions for installation in the wiki? Including `make test`? Did you source the environment variables? Could you post the actual commands you ran to install?

We can offer only limited help with integration problems, but I might guess the problem if I see enough info.

**Comment by ademcan** [comment]
Ok, I got it running with the example ecoli dataset, I guess there is something wrong in my config file. 
Thank you very much for your help and sorry for writing before proper testing.

**Comment by pb-cdunn** [comment]
I highly recommend putting some effort into acquiring the synth0 test-case. That runs in seconds and is therefore an excellent system integration test.

**Comment by Timothy-Amos** [comment]
Hi @ademcan, 

I came to this page because I got the exact same error message. If you were able to provide some more details about how you fixed this issue that might help me, if I can't figure it out myself, and whoever else passes this way in the future.

Thanks

**Comment by pb-cdunn** [comment]
This happens when there is an existing falcon installation, or when it already exists somewhere in your `PYTHONPATH`.

**Comment by pb-cdunn** [comment]
If you think that's not the case, then please post the exact steps you took to build, install, and run. You might be missing something in your environment.

**Comment by ademcan** [comment]
This error was due to some mis-configuration of the config file. I don't remember exactly what I did to correct it... but I had to play a lot with the different parameters.
For the installation procedure, I used the one without virtualenv, "The easy way"
https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation

**Comment by pb-cdunn** [comment]
> I don't remember exactly what I did to correct it.

Shoot. It could be helpful to others if you can remember.

> For the installation procedure, I used the one without virtualenv...

```
make config-edit-user
```

Good. That should set `PYTYHONUSERBASE` in your environment. You will need that and the PATH whenever you run.

I'm glad you got it working.

**Comment by Mr-Inamn** [comment]
Hi @ademcan,
I met the same problem and now I really suffer for that. For the installation procedure, I also used the the easy way. But the final test step went wrong. It appears as follows. Can anybody help me?

> make -C ./FALCON-make/ test
> make[1]: Entering directory `/public/home/lijing/software/FALCON-integrate/FALCON-make'
> make -C /public/home/lijing/software/FALCON-integrate/FALCON-examples test
> make[2]: Entering directory`/public/home/lijing/software/FALCON-integrate/FALCON-examples'
> python -c 'import pypeflow.common; print pypeflow.common'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named pypeflow.common
> make[2]: **\* [test] Error 1
> make[2]: Leaving directory `/public/home/lijing/software/FALCON-integrate/FALCON-examples'
> make[1]: *** [test] Error 2
> make[1]: Leaving directory`/public/home/lijing/software/FALCON-integrate/FALCON-make'

**Comment by pb-cdunn** [comment]
> ImportError: No module named pypeflow.common

Very simple integration problem. Python is not finding the `pypeflow` module, which you have installed somewhere. You probably did not source `env.sh` into your shell before running.

It is also possible that you have an old version of pypeflow already installed in your system Python. `PYTHONUSERBASE` should put your new pypeflow ahead of that if you did a `--user` install. But if you used **virtualenv**, you could have problems. Maybe ask from help from a sysadmin or Python expert locally? Please post your solution when you solve it.

**Comment by cgcjacobs** [comment]
I had the same problem as ademcan. After rerunning these steps in the Falcon-integrate folder:
```sh
make init
source env.sh
make config-edit-user
make -j all
make test 
```
It was solved for me.
