### ISSUE TITLE
Telling Falcon pipeline to stop after specific steps

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/FALCON-integrate#79]
Hi,

Is there a way to set up the cfg file (or another way) to tell Falcon to stop after specific steps?

For examples
- stop before merging las files in the job_xxxx subdirectories of 0-rawreads
- stop after doing all the work in 0-rawreads
- etc etc etc

best,

  John

**Comment by pb-cdunn** [comment]
Not yet. For now, you'd have to add that yourself, in your cloned repo.

**Comment by JohnUrban** [comment]
Thanks for the quick response. Would that be something trivial for me to do? If so, I'll attempt it. If not, then I suppose I will just have to kill running jobs for that purpose. What file(s) should I look into modifying?

**Comment by JohnUrban** [comment]
I guess it looks like modifications to `falcon_kit/run_support.py` and `falcon_kit/mains/run0.py` would be needed....

**Comment by pb-cdunn** [comment]
We use `run1.py` instead of `run0.py` now, but yes.

**Comment by JohnUrban** [comment]
Thanks.
