### ISSUE TITLE
'jobqueue' config parameter warning message

### ISSUE THREAD

**Issue by hp2048** [PacificBiosciences/FALCON-integrate#80]
Hi
I am getting the following warning for the release downloaded on 15th Aug 2016 as per the instruction.
`FALCON-integrate/FALCON/falcon_kit/run_support.py:324: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))`
I am still going through the test cases etc to figure out details about using the software suite on my system so I am not sure if this warning has any other implications or not. But just thought, would let you know.
Cheers
Hardip

**Comment by pb-cdunn** [comment]
That's not a problem, but I recommend removing all settings which produce this message.

Just be sure to look at how your jobs are actually submitted to your host-grid. The queue-name should be whatever you expect.
