### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by DongnaMa** [PacificBiosciences/FALCON-integrate#81]
Hello.
How can i know because of what the error occurs?
I get an error on run 'make test':

make -C ./FALCON-make/ test
make[1]: Entering directory `/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-make'
make -C /home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples test
make[2]: Entering directory`/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
python -c 'import pypeflow.common; print pypeflow.common'
<module 'pypeflow.common' from '/home/stu_madongna/miniconda2/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/common.pyc'>
python -c 'import falcon_kit; print falcon_kit.falcon'
<CDLL '/home/stu_madongna/miniconda2/lib/python2.7/site-packages/falcon_kit-0.7+git.85e41a6ab3bbeaece25f43e47c8f9a2cb9feb31a-py2.7-linux-x86_64.egg/ext_falcon.so', handle 1102800 at 7f1cc15db490>
make run-synth0
make[3]: Entering directory `/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
git-sym update run/synth0
git: 'check-ignore' is not a git command. See 'git --help'.
-> in dir 'run/synth0'
<- back to dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/ref.fasta'
symlink: 'run/synth0/data/synth0.fasta'
'run/synth0/data/ref.fasta' -> '../../../.git-sym/synth0.ref.fasta' does not exist
'run/synth0/data/synth0.fasta' -> '../../../.git-sym/synth0-circ-20.pb.fasta' does not exist
-> in dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/links'
-> in dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
make -j  -f /home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth0.ref.fasta'
make[4]: Entering directory`/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
make[4]: `synth0.ref.fasta' is up to date.
make[4]: Leaving directory`/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
make -j  -f /home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/git-sym.makefile 'synth0-circ-20.pb.fasta'
make[4]: Entering directory `/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
make[4]:`synth0-circ-20.pb.fasta' is up to date.
make[4]: Leaving directory `/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
<- back to dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples/.git/git-sym-local/links'
os.symlink('../cache/synth0-circ-20.pb.fasta', 'synth0-circ-20.pb.fasta')
os.symlink('../cache/synth0.ref.fasta', 'synth0.ref.fasta')
<- back to dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
git-sym show run/synth0
git: 'check-ignore' is not a git command. See 'git --help'.
-> in dir 'run/synth0'
<- back to dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/ref.fasta'
symlink: 'run/synth0/data/synth0.fasta'
. run/synth0/data/ref.fasta .git-sym/synth0.ref.fasta
. run/synth0/data/synth0.fasta  .git-sym/synth0-circ-20.pb.fasta
git-sym check run/synth0
git: 'check-ignore' is not a git command. See 'git --help'.
-> in dir 'run/synth0'
<- back to dir '/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
symlink: 'run/synth0/data/ref.fasta'
symlink: 'run/synth0/data/synth0.fasta'
cd run/synth0; fc_run.py fc_run.cfg logging.ini
Traceback (most recent call last):
  File "/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').require('falcon-kit==0.7+git.d51ec37a4012eed6743a8b1118070771128e039a')
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2900, in <module>
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2886, in _call_aside
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 644, in _build_master
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 657, in _build_from_requirements
  File "/home/stu_madongna/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 830, in resolve
pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.d51ec37a4012eed6743a8b1118070771128e039a' distribution was not found and is required by the application
make[3]: *** [run-synth0] Error 1
make[3]: Leaving directory`/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
make[2]: **\* [test] Error 2
make[2]: Leaving directory `/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-examples'
make[1]: *** [test] Error 2
make[1]: Leaving directory`/home/stu_madongna/pacbio_simu/shiyan/software/FALCON-integrate/FALCON-make'
make: **\* [test] Error 2

**Comment by pb-cdunn** [comment]
> in resolve pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.d51ec37a4012eed6743a8b1118070771128e039a' distribution was not found and is required by the application

Possibly you already have falcon_kit installed. Possibly you did not properly set `PYTHONUSERBASE` in your environment. Or if you are using a **virtualenv** installation, possibly you have something in your `PYTHONPATH` already.

It's very difficult to help with such integration problems remotely. This definitely works for us in TravisCI. See `travis.sh` for how we test it.
