### ISSUE TITLE
FALCON-integrate running problems.

### ISSUE THREAD

**Issue by WeichenZhou** [PacificBiosciences/FALCON-integrate#92]
Hi there,
I have just installed FALCON-integrate by using 

> git clone git://github.com/PacificBiosciences/FALCON-integrate.git
> cd FALCON-integrate
> git checkout master  # or whatever version you want
> make init
> source env.sh
> make config-edit-user
> make -j all
> make test  # to run a simple one
> 

And 'make test' looks fine.
When I was running my local job (job_type = local), it also looked alright.
However, when I was using qsub (job_type = sge), it came out the error information as:

> 
> [INFO]Setup logging from file "None".
> [INFO]fc_run started with configuration /home/arthurz/remills-scratch2/arthurz/16.10.10.Pacbio_Inv/16.10.28.Pacbio_validation/10.31.testforFALCON/flux
> /fc_run.cfg
> [WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
> [WARNING]HPC.daligner option "-dal" has changed to "-B". Correcting this for you.
> [INFO] No target specified, assuming "assembly" as target 
> [INFO]# of tasks in complete graph: 1
> [INFO]tick: 1, #updatedTasks: 0, sleep_time=0.000000
> [INFO]tick: 2, #updatedTasks: 0, sleep_time=0.100000
> [INFO]Running task from function task_make_fofn_abs_raw()
> [INFO]script_fn:'noop.sh'
> [INFO]jobid=Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878
> [INFO]starting job Job(jobid='Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878', cmd='/bin/bash noop.sh', rundir='/nfs/turbo/remillss
> cr/scratch2_trans/arthurz/16.10.10.Pacbio_Inv/16.10.28.Pacbio_validation/10.31.testforFALCON/flux', options={'job_queue': 'default', 'sge_option': '',
>  'job_type': 'sge'})
> [INFO]!qsub -N Jfaddbf7fb358bc -q default  -V -cwd -o stdout -e stderr -S /bin/bash /nfs/turbo/remillsscr/scratch2_trans/arthurz/16.10.10.Pacbio_Inv/1
> 6.10.28.Pacbio_validation/10.31.testforFALCON/flux/mypwatcher/wrappers/run-Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878.bash
> qsub: /nfs/turbo/remillsdata/local/apps/images/anaconda/2/lib/liblzma.so.5: no version information available (required by /lib64/libselinux.so.1)
> [qsub: illegal -c value]
> 
> usage: qsub [-a date_time] [-A account_string] [-b secs]
>     [-c [ none | { enabled | periodic | shutdown |
>     depth=<int> | dir=<path> | interval=<minutes>}... ]
>     [-C directive_prefix] [-d path] [-D path]
>     [-e path] [-h] [-I] [-j oe|eo|n] [-k {oe}] [-K <kill delay seconds>] 
>     [-l resource_list] [-m n|{abe}] [-M user_list] [-N jobname] [-o path] 
>     [-p priority] [-P proxy_user [-J <jobid]] [-q queue] [-r y|n] 
>     [-S path] [-t number_to_submit] [-T type]  [-u user_list] [-w] path
>     [-W additional_attributes] [-v variable_list] [-V ] [-x] [-X] [-z] [script]
> 
> [ERROR]In pwatcher.fs_based.cmd_run(), failed to submit background-job:
> MetaJobSge(MetaJob(job=Job(jobid='Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded7878', cmd='/bin/bash noop.sh', rundir='/nfs/turbo/remi
> llsscr/scratch2_trans/arthurz/16.10.10.Pacbio_Inv/16.10.28.Pacbio_validation/10.31.testforFALCON/flux', options={'job_queue': 'default', 'sge_option':
>  '', 'job_type': 'sge'}), lang_exe='/bin/bash'))
> Traceback (most recent call last):
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 520, in cmd_run
>     state.submit_background(bjob)
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 117, in submit_background
>     bjob.submit(self, exe, script_fn) # Can raise
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 296, in submit
>     system(sge_cmd, checked=True) # TODO: Capture q-jobid
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pwatcher/fs_based.py", line 539, in system
>     raise Exception('{} <- {!r}'.format(rc, call))
> Exception: 512 <- 'qsub -N Jfaddbf7fb358bc -q default  -V -cwd -o stdout -e stderr -S /bin/bash /nfs/turbo/remillsscr/scratch2_trans/arthurz/16.10.10.
> Pacbio_Inv/16.10.28.Pacbio_validation/10.31.testforFALCON/flux/mypwatcher/wrappers/run-Jfaddbf7fb358bccb296e270b8ef986acc5e127096a87b6ea0562d156dded78
> 78.bash'
> [WARNING]  File "/home/arthurz/app/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/home/arthurz/app/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
>     main(sys.argv)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 662, in main
>     main1(argv[0], args.config, args.logger)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 423, in main1
>     setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 457, in run
>     wf.refreshTargets([fofn_abs_task])
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
>     rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 657, in _refreshTargets
>     numAliveThreads = self.thread_handler.alive(task2thread.values())
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 199, in alive
>     fred.endrun('UNSUBMITTED')
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/pwatcher_bridge.py", line 92, in endrun
>     log.warning(''.join(traceback.format_stack()))
> 
> [ERROR]Task Fred{'URL': 'task:///home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'}
>  is UNSUBMITTED, meaning job-submission somehow failed. Possibly a re-start would work. Otherwise, you need to investigate.
> [INFO]Queued 'task:///home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw' ...
> [INFO]Failure ('fail'). Joining 'task:///home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py/task_make_fofn_abs_raw'...
> [CRITICAL]Any exception caught in RefreshTargets() indicates an unrecoverable error. Shutting down...
> /home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py:537: UserWarning: 
>             "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
>             "! Please wait for all threads / processes to terminate !"
>             "! Also, maybe use 'ps' or 'qstat' to check all threads,!"
>             "! processes and/or jobs are terminated cleanly.        !"
>             "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
>             
>   warnings.warn(shutdown_msg)
> [WARNING]#tasks=1, #alive=0
> Traceback (most recent call last):
>   File "/home/arthurz/app/FALCON-integrate/fc_env/bin/fc_run.py", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/home/arthurz/app/FALCON-integrate/FALCON/src/py_scripts/fc_run.py", line 5, in <module>
>     main(sys.argv)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 662, in main
>     main1(argv[0], args.config, args.logger)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 423, in main1
>     setNumThreadAllowed=PypeProcWatcherWorkflow.setNumThreadAllowed)
>   File "/home/arthurz/app/FALCON-integrate/FALCON/falcon_kit/mains/run1.py", line 457, in run
>     wf.refreshTargets([fofn_abs_task])
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 548, in refreshTargets
>     raise Exception('Caused by:\n' + tb)
> Exception: Caused by:
> Traceback (most recent call last):
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 523, in refreshTargets
>     rtn = self._refreshTargets(task2thread, objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
>   File "/home/arthurz/app/FALCON-integrate/pypeFLOW/pypeflow/controller.py", line 740, in _refreshTargets
>     raise TaskFailureError("Counted %d failure(s) with 0 successes so far." %failedJobCount)
> TaskFailureError: 'Counted 1 failure(s) with 0 successes so far.'
> 

And if I run fc_run.py in another terminal window locally, it also came out an error here:

 

> File "/home/arthurz/app/FALCON-integrate/fc_env/bin/fc_run.py", line 4, in <module>
>     __import__('pkg_resources').require('falcon-kit==0.7+git.91823bfc08f2f3f6c3e7e99be1dfc325c38556ec')
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2900, in <module>
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2886, in _call_aside
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 642, in _build_master
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 943, in require
>   File "/home/remills/apps/images/anaconda/2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 830, in resolve
> pkg_resources.DistributionNotFound: The 'falcon-kit==0.7+git.91823bfc08f2f3f6c3e7e99be1dfc325c38556ec' distribution was not found and is required by the application
> 
> 

I would appreciate if someone could tell me how to handle these bugs. Thank you so much.

**Comment by mhsieh** [comment]
You should be using pbs instead of sge.

**Comment by mhsieh** [comment]
That being said, let us find out a working configuration for you.

**Comment by mhsieh** [comment]
I think it should be safe to say that we can use `-cwd` in your case. I am very curious about if this `-w` option can used.

Basically you need to modify the pypeFlow code to replace `-cwd` with `-w \$PWD` ... can @pb-cdunn comment a bit?

**Comment by WeichenZhou** [comment]
Hi mhsieh,
Thank you for your quick and kind reply. As I understood, I should change the pypeFlow code to solve the pbs problem?
So another problem as I said is that my FALCON-intergrate can not run in another terminal window since falcon-kit can not be found... Could you know what to deal with that?

I appreciate your help.

**Comment by mhsieh** [comment]
Not finding the falcon-kit looks serious, did you do `. fc_env/bin/activate` ?

**Comment by WeichenZhou** [comment]
I did not do that (since I was not told to do). And after  `. fc_env/bin/activate`
 it says : 

> Error: no environment provided.

**Comment by pb-cdunn** [comment]
@mhsieh, This was not the user I referred to at stand-up, but yes, it is the same problem. I'm working a release to allow `sge_option` to be set by default in #93. Just a quick TravisCI problem to overcome first...

**Comment by pb-cdunn** [comment]
> Not finding the falcon-kit looks serious, did you do . fc_env/bin/activate ?

That would be for **virtualenv**, but you are not using virtualenv unless you set that up yourself and do a "system" install into it. More likely, you are doing a "usebase" install. For that, you need `PYTHONUSERBASE` in your environment (and also `PATH`) from `env.sh`.

**Comment by mhsieh** [comment]
Thank you Chris for clarification.

**Comment by pb-cdunn** [comment]
Try 1.8.0 (current tip of `master`):
- https://github.com/PacificBiosciences/FALCON-integrate/releases/tag/1.8.0
