### ISSUE TITLE
Number of cpus on a local job

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/FALCON-integrate#95]
I just pulled the most recent version of FALCON-integrate. I started up with the same .cfg script as before, including specification of 

job_type= local 

and 

pa_concurrent_jobs = 1
cns_concurrent_jobs = 1
ovlp_concurrent_jobs = 1

to tune overall cpu use. However the daligner processes are taking up all 56 vCPUs. Is there an additional flag needed to limit total processor allowance?

**Comment by pb-cdunn** [comment]
If you update FALCON, this is fixed. We will do a new release with this soon.
